// The circuit the landing page runs: comment-hold, filled from its own stated rule and frozen,
// saved with its codebook so the page can decode and simulate it the moment it opens instead of
// compiling first. It is the real proven netlist, not a drawing of one.
//
//   node scripts/build-demo.mjs   -> examples/comment-hold.demo.json
import { readFileSync, writeFileSync } from "node:fs";
import { codebookJson, fillDecision, freezeDecision, parseDecision, ruleFiller } from "../src/decision.mjs";
import { netlistJson } from "../src/job.mjs";

const spec = JSON.parse(readFileSync("examples/comment-hold.decision.json", "utf8"));
const d = parseDecision(spec);
const fill = await fillDecision(d, ruleFiller(d, spec.rule));
const frozen = freezeDecision(d, fill);
const c = frozen.certificate;
const demo = {
  _: "Generated by scripts/build-demo.mjs from comment-hold.decision.json and its own rule. The landing page runs this netlist.",
  codebook: codebookJson(d),
  question: d.question,
  netlist: netlistJson(d.name, frozen.circuit),
  proof: { nand: c.circuit.nand, rows: c.verification.rowsChecked, wrong: c.verification.wrong },
};
writeFileSync("examples/comment-hold.demo.json", `${JSON.stringify(demo)}\n`);
console.log(`examples/comment-hold.demo.json: ${demo.proof.nand} NAND, ${demo.proof.rows} rows, ${demo.proof.wrong} wrong`);
