// The decision flow, in a page.
//
// This is where it belongs. The step measured to matter most - twenty situations put to a
// person who cannot see what the model answered - is a survey, and answering a survey by
// typing numbers into a terminal is silly. The threshold sweep is a table. The verdict is one
// sentence in a box. All of that reads better here than anywhere.
//
// Everything goes through this machine's own server: the decision model's replies carry no
// access-control-allow-origin, so a page cannot call it, and that turned out better - the key
// stays in ~/.config and never enters a browser.
import { decodeCircuit, hexToBytes, simulate } from "../src/netlist.mjs";
import { decisionPinNames, fillDecision, parseDecision } from "../src/decision.mjs";
import { majorityFiller, textFiller } from "../src/chatfill.mjs";
import { diagramLayout } from "./model.mjs";
import { renderLanding } from "./landing.mjs";
import { createTour } from "./tour.mjs";
import { codebookPrompt, settleWidths } from "../src/draft.mjs";
import { modelRequest, replyText, specFromReply } from "../src/describe.mjs";
import { trialUrl } from "../src/trial.mjs";

// Two homes for the same page. Run locally (npm run ui), it talks to this machine's server,
// which holds the decision-model key if you have one. Served as a plain website (gatecraft.fun),
// there is no server: the very same methods are imported and run here in the browser, with no
// key, so a fill uses the free trial or your own model. Which one is decided once, by asking.
let local = null;
const hasServer = () => (local ??= fetch(new URL("../api", import.meta.url))
  .then((r) => (r.ok ? r.json() : null))
  .then((body) => Boolean(body?.ok))
  .catch(() => false));
let inPage = null;
const pageApi = () => (inPage ??= import("../src/api.mjs"));

const api = async (method, params = {}) => {
  if (await hasServer()) {
    const response = await fetch(new URL("../api", import.meta.url), {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ method, params }),
    });
    const body = await response.json();
    if (!body.ok) throw new Error(body.error?.message ?? `${method} failed`);
    return body.result;
  }
  const { handleApi } = await pageApi();
  // On the website a visitor's own decision-model key lives only in this page; the browser cannot
  // call the model directly, so it goes through the free-fill service, which forwards it uncounted.
  const own = decideState.jevKey || null;
  const { body } = await handleApi({ method, params }, { decisionKey: own, jevProxy: own ? (decideState.forwarder || trialUrl()) : null });
  if (!body.ok) throw new Error(body.error?.message ?? `${method} failed`);
  return body.result;
};

export const decideState = {
  specText: "",
  spec: null,
  read: null,
  fill: null,
  frozen: null,
  sheet: null,
  at: 0,
  calibration: null,
  busy: "",
  error: "",
  keyPresent: null,
};

// Twenty blind answers are the scarcest thing this page collects - they cost a person real
// attention and cannot be regenerated by any model. Losing them to a reload is the worst thing
// the page could do, so the work in progress is kept in this browser's storage. Only what was
// typed, fetched or answered is kept; the decoded circuit is rebuilt from its bytes. Storage
// can be missing or full (private windows, quotas), and then the page simply forgets, as before.
const SAVED = "gatecraft.decide.v1";
const KEPT = ["sentence", "widened", "specText", "spec", "read", "fill", "fillStats", "filledBy", "frozen", "sheet", "at", "calibration", "codes"];

function restore() {
  try {
    const saved = JSON.parse(localStorage.getItem(SAVED) ?? "null");
    if (saved && typeof saved === "object") for (const key of KEPT) if (key in saved) decideState[key] = saved[key];
  } catch { /* nothing kept, or unreadable: start fresh */ }
}

function persist() {
  try { localStorage.setItem(SAVED, JSON.stringify(Object.fromEntries(KEPT.map((k) => [k, decideState[k] ?? null])))); }
  catch { /* storage full or refused: this visit still works, it just will not survive a reload */ }
}

export function forgetDecision() {
  for (const key of KEPT) decideState[key] = key === "specText" ? "" : key === "at" ? 0 : null;
  decideState.error = "";
  try { localStorage.removeItem(SAVED); } catch { /* nothing to remove */ }
}

restore();

// A visitor's own decision-model key, on the website. Held in memory; written to this browser's
// storage only when they tick "remember", and removable with one click. Never part of the saved
// work, so "Start over" does not carry it into a screenshot or a shared machine by surprise.
const JEV_SLOT = "gatecraft.jev.v1";
try { decideState.jevKey = localStorage.getItem(JEV_SLOT) || ""; decideState.jevRemember = Boolean(decideState.jevKey); } catch { decideState.jevKey = ""; }
// Which forwarder carries a visitor's own key. gatecraft's by default; anyone who would rather
// their key touch no server but their own deploys forwarder/ and points the page at it.
const FWD_SLOT = "gatecraft.forwarder.v1";
try { decideState.forwarder = localStorage.getItem(FWD_SLOT) || ""; } catch { decideState.forwarder = ""; }
function setForwarder(url) {
  decideState.forwarder = url;
  try { if (url) localStorage.setItem(FWD_SLOT, url); else localStorage.removeItem(FWD_SLOT); } catch { /* lasts this visit */ }
}
const DEPLOY_FORWARDER = "https://deploy.workers.cloudflare.com/?url=https://github.com/BruceLanLan/gatecraft/tree/main/forwarder";

function setJevKey(key, remember) {
  decideState.jevKey = key.trim();
  decideState.jevRemember = remember;
  try { if (remember && decideState.jevKey) localStorage.setItem(JEV_SLOT, decideState.jevKey); else localStorage.removeItem(JEV_SLOT); } catch { /* storage refused: it lasts this visit */ }
}

// The person's own model, as the rest of the page already has it set up: provider, address,
// model name and key all live in app.mjs, and the key never leaves this browser except to that
// provider. This page only borrows it to draft a codebook - filling still goes through the
// decision model on the server, because drafting and filling are different jobs.
const modelAccess = { get: () => null, open: () => {} };

// The gate drawing lives in app.mjs with the rest of the circuit views; this page borrows it
// rather than growing a second one, so a decision's circuit looks exactly like every other
// circuit in gatecraft - the same NAND shapes, the same lit wires.
let drawCircuit = null;
export function useDiagram(draw) { drawCircuit = draw; }
export function useModel(get, open) {
  modelAccess.get = get;
  modelAccess.open = open;
}

// A model drafts; code judges the shape; a person judges the buckets. Two tries, the second
// told exactly what was wrong with the first - the same repair the CLI's draft command does.
// A model on the visitor's own computer, called from the website: the browser refuses it and so
// does Ollama unless told this site may call it. Said plainly rather than as "failed to fetch".
const localBlocked = (url) => decideState.hosted && /^http:\/\/(127\.0\.0\.1|localhost|\[::1\])[:/]/.test(url);

async function draftCodebook(sentence, t) {
  const m = modelAccess.get();
  let why = "";
  for (let attempt = 1; attempt <= 2; attempt++) {
    const content = codebookPrompt(sentence) + (why ? `\n\nYour previous attempt was rejected: ${why}\nFix exactly that.` : "");
    const { url, init } = modelRequest({ ...m, messages: [{ role: "user", content }] });
    let response;
    try { response = await fetch(url, { ...init, signal: AbortSignal.timeout(180_000) }); }
    catch (error) { throw new Error(localBlocked(url) ? t("decLocalBlocked") : t("decDraftUnreachable", new URL(url).origin, error.name === "TimeoutError" ? "timed out" : error.message)); }
    let body = null;
    try { body = await response.json(); } catch { /* an error page: the status says enough */ }
    const text = replyText(m.provider, response.status, body);
    try {
      const { spec, fixed } = settleWidths(specFromReply(text));
      parseDecision(spec);
      return { spec, fixed };
    } catch (error) { why = error.message; }
  }
  throw new Error(t("decDraftFailed", why));
}

const el = (tag, className, text) => {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
};

function card(title, step) {
  const section = el("section", "card");
  section.dataset.step = String(step);
  const head = el("h2", "step");
  head.append(el("span", "num", String(step)), el("span", null, title));
  section.append(head);
  return section;
}

// What a stranger sees first. The page opens here now, so the first screen has to answer "what
// is this and should I bother" before it asks for a JSON file - and it has to say the two things
// that send most people away (observations must already be discrete codes; the answer may be
// "do not delegate this") up front rather than after they have spent an hour.
const EXAMPLES = [
  ["comment-hold", "decEx_commentHold"],
  ["refund-call", "decEx_refundCall"],
];

// The flow's actions, for the guided tour: the same steps a visitor takes by clicking.
async function loadExample(name) {
  const spec = await (await fetch(new URL(`../examples/${name}.decision.json`, import.meta.url))).json();
  decideState.specText = JSON.stringify(spec, null, 2);
  decideState.read = decideState.fill = decideState.fillStats = decideState.frozen = decideState.sheet = decideState.calibration = null;
  decideState.error = "";
}

// After a fill, the rest is the same whoever answered: freeze and prove, and draw the questions
// for the person from the confidences the fill carries.
async function freezeAndDraw(fill) {
  decideState.fill = fill;
  decideState.codes = {};
  decideState.frozen = await api("decision.freeze", { spec: decideState.spec, fill });
  decideState.sheet = (await api("decision.anchors", { spec: decideState.spec, fill, count: 20 })).sheet;
  decideState.at = 0;
}

async function fillByRule() {
  const out = await api("decision.fill", { spec: decideState.spec, rule: decideState.spec.rule });
  decideState.fillStats = out;
  decideState.filledBy = "rule";
  await freezeAndDraw(out.fill);
}

let tour = null;
function tourFor(t) {
  tour ??= createTour({
    t,
    actions: { loadExample, readBack: readBackNow, fillByRule, poke: async (codes) => { decideState.codes = { ...(decideState.codes ?? {}), ...codes }; } },
    rerender: () => redrawDecide(),
  });
  return tour;
}

export function redrawDecide() { if (keyTarget) renderDecide(keyTarget.root, keyTarget.t); }

function startOwn() {
  const box = document.querySelector("#decide .draft-input");
  box?.scrollIntoView({ block: "center", behavior: "smooth" });
  box?.focus({ preventScroll: true });
}

async function readBackNow() {
  decideState.error = "";
  try {
    // Pure JSON, or a whole reply pasted from an AI chat with prose and fences around it. Widths
    // too small for their own codes are settled the same way a drafted file's are.
    let spec;
    try { spec = JSON.parse(decideState.specText); }
    catch {
      const settled = settleWidths(specFromReply(decideState.specText));
      spec = settled.spec;
      decideState.widened = settled.fixed;
      decideState.specText = JSON.stringify(spec, null, 2);
    }
    decideState.read = await api("decision.review", { spec });
    decideState.spec = spec;
    decideState.fill = decideState.frozen = decideState.sheet = decideState.calibration = null;
    decideState.codes = {};
  } catch (error) { decideState.error = String(error.message); decideState.read = null; }
}

// One sentence in, a codebook out, and straight into the read-back - because the draft is the
// model's guess and the read-back's notes (the wall, the safe action) are where a person checks
// it. Nobody should be handed a drafted codebook without that step in front of them.
function renderDraft(t, redraw) {
  const box = el("div", "draft");
  box.append(el("p", "hint", t("decDraftOr")));
  const line = el("textarea", "draft-input");
  line.rows = 2;
  line.placeholder = t("decDraftPlaceholder");
  line.value = decideState.sentence ?? "";
  line.addEventListener("input", () => { decideState.sentence = line.value; });
  box.append(line);

  const m = modelAccess.get();
  const bar = el("div", "row");
  const go = el("button", "primary", decideState.busy === "draft" ? t("decDrafting") : t("decDraftGo"));
  go.disabled = Boolean(decideState.busy) || !m?.ready;
  go.addEventListener("click", async () => {
    const sentence = (decideState.sentence ?? "").trim();
    if (!sentence) { decideState.error = t("decDraftEmpty"); redraw(); return; }
    decideState.busy = "draft"; decideState.error = ""; redraw();
    try {
      const { spec, fixed } = await draftCodebook(sentence, t);
      decideState.specText = JSON.stringify(spec, null, 2);
      await readBackNow();
      decideState.widened = fixed;
    } catch (error) { decideState.error = String(error.message); }
    decideState.busy = ""; redraw();
  });
  const pick = el("button", "ghost", t("decDraftPick"));
  pick.addEventListener("click", () => modelAccess.open());
  // No model set up at all: the same prompt, for any AI chat the visitor already uses. They paste
  // the whole reply into the box below; the read-back finds the JSON in it.
  const copy = el("button", "ghost", decideState.copied ? t("decDraftCopied") : t("decDraftCopy"));
  copy.addEventListener("click", async () => {
    const sentence = (decideState.sentence ?? "").trim();
    if (!sentence) { decideState.error = t("decDraftEmpty"); redraw(); return; }
    const prompt = codebookPrompt(sentence);
    try { await navigator.clipboard.writeText(prompt); decideState.copied = true; decideState.promptShown = null; }
    catch { decideState.copied = false; decideState.promptShown = prompt; }
    decideState.error = "";
    redraw();
  });
  bar.append(go, copy, pick);
  box.append(bar);
  box.append(el("p", "hint", m?.ready ? t("decDraftModel", m.label) : t("decDraftNoModel")));
  if (decideState.copied) box.append(el("p", "result", t("decDraftPasteBack")));
  if (decideState.promptShown) {
    const shown = el("textarea", "draft-prompt mono");
    shown.rows = 6; shown.readOnly = true; shown.value = decideState.promptShown;
    box.append(el("p", "hint", t("decDraftSelect")), shown);
  }
  return box;
}

// Step 1: the codebook, and the read-back that makes a person look at the buckets.
function renderSpec(root, t, redraw) {
  const section = card(t("decSpecTitle"), 1);
  section.append(el("p", "hint", t("decSpecHint")));

  // Nobody writes one of these from a blank box. These two are real decisions from this repo,
  // both already carried through anchors, so the first run shows the whole flow rather than a
  // parse error.
  const picks = el("div", "row examples");
  picks.append(el("span", "hint", t("decExamples")));
  for (const [name, key] of EXAMPLES) {
    const button = el("button", "ghost", t(key));
    button.addEventListener("click", async () => {
      try {
        const spec = await (await fetch(new URL(`../examples/${name}.decision.json`, import.meta.url))).json();
        decideState.specText = JSON.stringify(spec, null, 2);
        decideState.read = decideState.fill = decideState.frozen = decideState.sheet = decideState.calibration = null;
        decideState.error = "";
      } catch { decideState.error = t("decExFailed"); }
      redraw();
    });
    picks.append(button);
  }
  section.append(picks);
  section.append(renderDraft(t, redraw));
  const area = el("textarea", "spec-input");
  area.rows = 8;
  area.placeholder = t("decSpecPlaceholder");
  area.value = decideState.specText;
  area.addEventListener("input", () => { decideState.specText = area.value; });
  section.append(area);

  const bar = el("div", "row");
  const read = el("button", "primary", t("decRead"));
  read.addEventListener("click", async () => { decideState.widened = null; await readBackNow(); redraw(); });
  bar.append(read);
  section.append(bar);

  if (decideState.read) {
    // The codebook itself belongs in monospace - it is a table of codes. What does not is the
    // part that is advice: the buckets that look like they live on the far side of the wall,
    // and the safe action, which is the field a model gets wrong in the way that matters. Those
    // were scrolling past inside the blob; they come out above it.
    const notes = [...(decideState.read.notes ?? [])];
    for (const w of decideState.widened ?? []) notes.unshift({ about: w.field, kind: "width", says: t("decWidened", w.field, w.from, w.to) });
    if (notes.length) {
      const list = el("div", "readnotes");
      list.append(el("p", "hint", t("decNotesTitle", notes.length)));
      for (const note of notes) {
        const item = el("div", `readnote${note.kind === "safe" ? " safe" : ""}`);
        item.append(el("span", "note-about mono", note.about));
        item.append(el("span", null, note.says));
        list.append(item);
      }
      section.append(list);
    }
    section.append(el("pre", "readback mono", decideState.read.text));
  }
  return section;
}

// Step 2: answer every situation, then freeze and prove it.
// Where a decision-model key comes from, said step by step, because "get a key" is where most
// people stop. On the website the key is pasted here; run locally it goes in a file the server
// reads. Either way the same four steps.
function renderJevKey(t, redraw) {
  const site = decideState.hosted;
  const box = el("details", "jevkey");
  box.open = Boolean(decideState.jevOpen) || (decideState.keyPresent === false && !(decideState.trial?.available && decideState.trial.left > 0));
  box.addEventListener("toggle", () => { decideState.jevOpen = box.open; });
  const summary = el("summary", null, decideState.jevKey && site ? t("jevUsing", decideState.jevKey.slice(-4)) : !site && decideState.keyPresent ? t("jevSavedSummary") : t("jevSummary"));
  box.append(summary);
  const steps = el("ol", "jev-steps");
  const link = (href, text) => { const a = el("a", null, text); a.href = href; a.target = "_blank"; a.rel = "noopener"; return a; };
  const s1 = el("li"); s1.append(t("jevStep1a"), " ", link("https://console.typesafe.ai/", "console.typesafe.ai"), " ", t("jevStep1b"));
  const s2 = el("li"); s2.append(t("jevStep2a"), " ", link("https://console.typesafe.ai/keys", "console.typesafe.ai/keys"), " ", t("jevStep2b"));
  const s3 = el("li", null, site ? t("jevStep3Site") : t("jevStep3Local"));
  steps.append(s1, s2, s3, el("li", null, t("jevStep4")));
  box.append(steps);
  if (!site) {
    // Run locally: the server keeps the key in ~/.config/gatecraft/jev.token and reads it on every
    // fill. The page can write it there for you; the terminal commands are for anyone who prefers
    // them, one per shell, because printf does not exist in PowerShell.
    if (decideState.keyPresent) {
      box.append(el("p", "result", t("jevSavedLocal")));
      const forget = el("button", "ghost", t("jevForgetLocal"));
      forget.addEventListener("click", async () => { try { await api("key.forget"); } catch (error) { decideState.error = String(error.message); } await probeKey(); redraw(); });
      box.append(forget);
    } else {
      const row = el("div", "row jev-row");
      const input = el("input", "jev-input mono");
      input.type = "password";
      input.id = "jev-key-local";
      input.placeholder = t("jevPlaceholder");
      input.autocomplete = "off";
      const save = el("button", null, t("jevSaveLocal"));
      save.addEventListener("click", async () => {
        decideState.error = "";
        try {
          const r = await api("key.save", { key: input.value });
          if (r.overriddenByEnv) decideState.error = t("jevEnvOverride");
        } catch (error) { decideState.error = String(error.message); }
        await probeKey();
        redraw();
      });
      row.append(input, save);
      box.append(row);
    }
    const terminal = el("details", "jev-terminal");
    terminal.append(el("summary", null, t("jevTerminal")));
    terminal.append(el("p", "hint", "macOS / Linux"));
    terminal.append(el("pre", "mono jev-cmd", "mkdir -p ~/.config/gatecraft && printf '%s' 'YOUR_KEY' > ~/.config/gatecraft/jev.token && chmod 600 ~/.config/gatecraft/jev.token"));
    terminal.append(el("p", "hint", "Windows (PowerShell)"));
    terminal.append(el("pre", "mono jev-cmd", "New-Item -ItemType Directory -Force \"$HOME\\.config\\gatecraft\" | Out-Null; Set-Content -NoNewline -Path \"$HOME\\.config\\gatecraft\\jev.token\" -Value 'YOUR_KEY'"));
    terminal.append(el("p", "hint", t("jevLocalReload")));
    box.append(terminal);
    return box;
  }
  const row = el("div", "row jev-row");
  const input = el("input", "jev-input mono");
  input.type = "password";
  input.id = "jev-key";
  input.placeholder = t("jevPlaceholder");
  input.autocomplete = "off";
  input.value = decideState.jevKey ?? "";
  const remember = el("label", "jev-remember");
  const tick = el("input");
  tick.type = "checkbox";
  tick.id = "jev-remember";
  tick.checked = Boolean(decideState.jevRemember);
  remember.append(tick, " ", t("jevRemember"));
  const use = el("button", null, t("jevUse"));
  use.addEventListener("click", async () => {
    setJevKey(input.value, tick.checked);
    decideState.jevOpen = false;
    await probeKey();
    redraw();
  });
  row.append(input, use);
  box.append(row, remember);
  if (decideState.jevKey) {
    const forget = el("button", "ghost", t("jevForget"));
    forget.addEventListener("click", async () => { setJevKey("", false); await probeKey(); redraw(); });
    box.append(forget);
  }
  box.append(el("p", "hint", t("jevPrivacy")));

  // Where the calls go, and how to make that nobody's server but your own.
  const via = decideState.forwarder || trialUrl() || "";
  const route = el("details", "jev-route");
  route.open = Boolean(decideState.fwdOpen);
  route.addEventListener("toggle", () => { decideState.fwdOpen = route.open; });
  route.append(el("summary", null, t("jevVia", via.replace(/^https:\/\//, ""))));
  route.append(el("p", "hint", t("jevFwdHow")));
  const deploy = el("a", "jev-deploy", t("jevFwdDeploy"));
  deploy.href = DEPLOY_FORWARDER; deploy.target = "_blank"; deploy.rel = "noopener";
  route.append(deploy);
  const fwdRow = el("div", "row jev-row");
  const fwd = el("input", "jev-input mono");
  fwd.id = "jev-forwarder";
  fwd.placeholder = "https://gatecraft-forwarder.<you>.workers.dev";
  fwd.value = decideState.forwarder ?? "";
  const save = el("button", null, t("jevFwdSave"));
  save.addEventListener("click", () => {
    const url = fwd.value.trim().replace(/\/+$/, "");
    if (url && !/^https:\/\/[^\s/]+(\/[^\s]*)?$/.test(url)) { decideState.error = t("jevFwdBad"); redraw(); return; }
    decideState.error = "";
    setForwarder(url);
    redraw();
  });
  fwdRow.append(fwd, save);
  route.append(fwdRow);
  if (decideState.forwarder) {
    const back = el("button", "ghost", t("jevFwdReset"));
    back.addEventListener("click", () => { setForwarder(""); redraw(); });
    route.append(back);
  }
  route.append(el("p", "hint", t("jevLocalAlt")));
  route.append(el("pre", "mono jev-cmd", "git clone https://github.com/BruceLanLan/gatecraft && cd gatecraft && npm run ui"));
  box.append(route);
  return box;
}

function renderFill(root, t, redraw) {
  const section = card(t("decFillTitle"), 2);
  const site = decideState.hosted;
  section.append(el("p", "hint", t(site ? "decFillHintSite" : "decFillHint")));
  // Without a key: a free fill if any are left, and always the ways to not need one.
  const freeLeft = decideState.keyPresent === false && decideState.trial?.available ? decideState.trial.left : 0;
  if (decideState.keyPresent === false) section.append(el("p", freeLeft > 0 ? "hint" : "warn", freeLeft > 0 ? t(site ? "decTrialOfferSite" : "decTrialOffer", freeLeft, decideState.trial.limit) : decideState.trial?.available ? t(site ? "decTrialGoneSite" : "decTrialGone", decideState.trial.limit) : t(site ? "decNoKeySite" : "decNoKey")));

  // Two sources, because a page that can do nothing without a key is a page most visitors
  // bounce off. Asking the model is the real thing; filling from a rule the file already
  // states asks nobody, needs no key, and still carries the whole rest of the flow - freeze,
  // proof, poke it, twenty questions. It is also honest about what it is: a decision you could
  // already write as a rule is one the calibration at the end ought to refuse.
  const fillWith = async (rule) => {
    decideState.busy = "fill"; decideState.error = ""; renderDecide(root, t);
    try {
      const out = await api("decision.fill", { spec: decideState.spec, ...(rule ? { rule } : {}) });
      // Nothing answered is not a fill to freeze: say what the model said instead of carrying an
      // empty table into the proof and failing three steps later with something opaque.
      if (!out.answered) throw new Error(t("decNothingAnswered", out.fill.rows.find((r) => r?.error)?.error ?? ""));
      decideState.fillStats = out;
      if (out.trial && decideState.trial) decideState.trial.left = out.trial.left;
      await probeKey();
      decideState.filledBy = rule ? "rule" : "model";
      await freezeAndDraw(out.fill);
    } catch (error) { decideState.error = String(error.message); }
    decideState.busy = ""; redraw();
  };

  // The person's own model, asked from this page. A chat model's self-reported confidence was
  // measured to carry nothing, so each situation is asked ASKS times and the confidence is how
  // often the answers agreed: at three asks and the usual 0.7 threshold, only a unanimous row
  // is acted on, and those were measured to reproduce 96-98% of the time. Nothing here goes
  // through this server: the prompt goes from the browser to the provider, with the key that
  // is already in this page for drafting.
  const legal = decideState.read?.legal ?? 0;
  const m = modelAccess.get();
  const calls = legal * ASKS;
  const fillOwn = async () => {
    decideState.busy = "own"; decideState.error = ""; decideState.progress = { done: 0, total: legal }; renderDecide(root, t);
    try {
      const d = parseDecision(decideState.spec);
      const ask = async (prompt) => {
        const { url, init } = modelRequest({ ...m, messages: [{ role: "user", content: prompt }] });
        let response;
        try { response = await fetch(url, { ...init, signal: AbortSignal.timeout(120_000) }); }
        catch (error) { throw new Error(localBlocked(url) ? t("decLocalBlocked") : t("decDraftUnreachable", new URL(url).origin, error.name === "TimeoutError" ? "timed out" : error.message)); }
        let body = null;
        try { body = await response.json(); } catch { /* the status says enough */ }
        return replyText(m.provider, response.status, body);
      };
      const one = textFiller(d, { ask, source: "chat", model: m.label });
      const local = /^http:\/\/(127\.0\.0\.1|localhost)/.test(String(m.baseUrl ?? ""));
      let shown = 0;
      const fill = await fillDecision(d, majorityFiller(one, ASKS), {
        asksPerRow: ASKS,
        concurrency: local ? 2 : 6,
        onRow: () => {
          decideState.progress.done += 1;
          // Redraw at most every few rows; a full redraw per answer would thrash the page.
          if (decideState.progress.done - shown >= Math.max(1, Math.floor(legal / 40)) || decideState.progress.done === legal) { shown = decideState.progress.done; renderDecide(root, t); }
        },
      });
      const rows = fill.rows.filter(Boolean);
      const answered = rows.filter((r) => r.choice);
      decideState.fillStats = { answered: answered.length, legal, failed: rows.filter((r) => r.source === "failed").length, settled: answered.filter((r) => (r.confidence ?? 0) >= d.threshold).length };
      decideState.filledBy = "own";
      if (!answered.length) throw new Error(t("decOwnNothing", rows.find((r) => r.error)?.error ?? ""));
      await freezeAndDraw(fill);
    } catch (error) { decideState.error = String(error.message); }
    decideState.busy = ""; decideState.progress = null; redraw();
  };

  const bar = el("div", "row");
  const go = el("button", "primary", decideState.busy === "fill" ? t("decFilling") : t("decFill"));
  go.disabled = Boolean(decideState.busy) || (decideState.keyPresent === false && freeLeft <= 0);
  if (decideState.keyPresent === false && freeLeft > 0 && decideState.busy !== "fill") go.textContent = t("decFillTrial", freeLeft);
  go.addEventListener("click", () => fillWith(null));
  bar.append(go);
  const own = el("button", decideState.keyPresent === false ? "primary" : "ghost", decideState.busy === "own" && decideState.progress ? t("decOwnProgress", decideState.progress.done, decideState.progress.total) : t("decFillOwn", calls));
  own.disabled = Boolean(decideState.busy) || !m?.ready || legal > OWN_MAX;
  own.addEventListener("click", fillOwn);
  bar.append(own);
  const rule = typeof decideState.spec?.rule === "string" ? decideState.spec.rule : null;
  if (rule) {
    const byRule = el("button", "ghost", t("decFillByRule"));
    byRule.disabled = Boolean(decideState.busy);
    byRule.addEventListener("click", () => fillWith(rule));
    bar.append(byRule);
  }
  section.append(bar);
  section.append(el("p", "hint", !m?.ready ? t("decOwnNoModel") : legal > OWN_MAX ? t("decOwnTooMany", legal, OWN_MAX) : t("decOwnHint", m.label, calls)));
  // The fill buttons come first; where a key comes from sits under them.
  section.append(renderJevKey(t, redraw));

  if (decideState.fillStats) {
    const s = decideState.fillStats;
    section.append(el("p", "result", decideState.filledBy === "rule" ? t("decFilledRule", s.answered, s.legal) : t("decFilled", s.answered, s.settled, s.legal)));
    section.append(el("p", "hint", decideState.filledBy === "rule" ? t("decFilledByRule") : decideState.filledBy === "own" ? t("decFilledByOwn", ASKS) : t("decFilledByModel")));
    if (decideState.fillStats.trial) section.append(el("p", "warn", t("decTrialUsed", decideState.fillStats.trial.left, decideState.fillStats.trial.limit)));
  }
  if (decideState.frozen) {
    const c = decideState.frozen.certificate;
    section.append(el("p", "result", t("decFrozen", c.circuit.nand, c.verification.rowsChecked, decideState.frozen.review.length)));
    section.append(el("p", "warn", t("decProofNotPolicy")));
    section.append(renderTry(t, redraw));
  }
  return section;
}

// Asks per situation when the person's own chat model fills the table, and how many situations
// that is allowed for from a browser tab: 512 situations is already 1,536 calls on their bill.
const ASKS = 3;
const OWN_MAX = 512;

// Poke the thing that was just built.
//
// The gallery lets you press the buttons on a circuit the moment it compiles, and that is the
// part of this page people actually play with. A decision had no equivalent: you got a gate
// count and a row count and nothing to touch. This runs THE NETLIST - decoded and simulated
// here in the page, the same bytes the certificate is about - so what you poke is the thing
// that would ship, not a preview of it. Clicking a code with no phrase is worth doing at least
// once: the answer falls to safe with review set, and no model, table or judgement is involved.
function circuitOf() {
  const net = decideState.frozen?.netlist;
  if (!net) return null;
  if (decideState.circuitFor !== net.netlistHex) {
    decideState.circuit = decodeCircuit(hexToBytes(net.netlistHex), net.nIn, net.nOut);
    decideState.circuitFor = net.netlistHex;
  }
  return decideState.circuit;
}

function renderTry(t, redraw) {
  const book = decideState.frozen.codebook;
  const net = decideState.frozen.netlist;
  const box = el("div", "tryit");
  box.append(el("h3", "tryit-title", t("decTryTitle")));
  box.append(el("p", "hint", t("decTryHint")));

  decideState.codes ??= {};
  let row = 0, shift = 0, illegalField = null;
  for (const f of book.observe) {
    const legal = Object.keys(f.values).map(Number).sort((a, b) => a - b);
    if (decideState.codes[f.field] === undefined) decideState.codes[f.field] = legal[0];
    const chosen = decideState.codes[f.field];
    if (!legal.includes(chosen) && illegalField === null) illegalField = f.field;
    row |= chosen << shift;
    shift += f.width;

    const line = el("div", "try-line");
    line.append(el("span", "sit-field", f.field));
    const picks = el("div", "try-picks");
    for (let code = 0; code < 2 ** f.width; code++) {
      const known = legal.includes(code);
      const button = el("button", `try-code${chosen === code ? " on" : ""}${known ? "" : " unknown"}`,
        known ? f.values[code] : t("decTryNoPhrase", code));
      button.addEventListener("click", () => { decideState.codes[f.field] = code; redraw(); });
      picks.append(button);
    }
    line.append(picks);
    box.append(line);
  }

  const out = simulate(circuitOf(), Array.from({ length: net.nIn }, (_, i) => (row >>> i) & 1), new Uint8Array(0));
  let code = 0;
  for (let b = 0; b < book.act.bits; b++) code |= (out.outputs[b] ? 1 : 0) << b;
  const review = Boolean(out.outputs[book.act.bits]);
  const choice = book.act.choices[code] ?? book.act.choices.find((c) => c.choice === book.act.safe);

  const answer = el("div", `try-answer${review ? " reviewing" : ""}`);
  answer.append(el("span", "try-label", t("decTryAnswer")));
  answer.append(el("strong", "try-choice", choice.phrase));
  answer.append(el("span", "try-name mono", choice.choice));
  answer.append(el("span", "try-flag", review ? t("decTryReview") : t("decTryActs")));
  box.append(answer);
  if (illegalField) box.append(el("p", "warn", t("decTryIllegalRow", illegalField)));

  // The circuit itself, lit by the situation picked above. This is the part the rest of
  // gatecraft has always shown and the decision view did not: the thing that was proven is a
  // few dozen NAND gates, and you can watch every one of them decide.
  const layout = drawCircuit ? diagramLayout(circuitOf()) : null;
  if (layout) {
    const names = decisionPinNames(parseDecision(decideState.spec));
    const wrap = el("div", "try-circuit");
    const head = el("div", "try-circuit-head");
    head.append(el("span", "try-label", t("decCircuitTitle", net.nand ?? circuitOf().elements.length)), el("span", "hint", t("decCircuitLit")));
    wrap.append(head, drawCircuit(layout, out.signals, { names }));
    box.append(wrap);
  } else if (drawCircuit) {
    box.append(el("p", "hint", t("decCircuitTooBig")));
  }
  return box;
}

// What to do with the file: the three lines of code, written with this decision's own field
// names and codes, and the same thing as words to hand a coding agent - because the step people
// get wrong is turning their program's data into the codes, and that is theirs to write.
function useItText(spec, name) {
  const fields = Object.entries(spec.observe);
  const choices = Object.keys(spec.act.choices);
  const codeLines = fields.map(([f, v]) => `//   ${f}: ${Object.entries(v.values).map(([c, p]) => `${c} = ${p}`).join(" · ")}`);
  const code = [
    `import { decide } from "./${name}";`,
    "",
    "// Your program turns what it already knows into these codes:",
    ...codeLines,
    `const { action, review } = decide({ ${fields.map(([f]) => f).join(", ")} });`,
    "",
    `if (review) handToAPerson();   // a code with no meaning, or a case it was not sure of`,
    `else ${choices.length === 2 ? `if (action === "${choices[0]}") { /* ${spec.act.choices[choices[0]]} */ } else { /* ${spec.act.choices[choices[1]]} */ }` : `act(action);          // one of: ${choices.join(" | ")}`}`,
  ].join("\n");
  const agent = [
    `Add ${name} to this project. It is a frozen, proven decision: "${spec.question}"`,
    "It exports decide(codes), which returns { action, review }.",
    "Write one small function that turns our own data into these codes, exactly as described:",
    ...fields.map(([f, v]) => `- ${f} (${v.raw ?? "see the codebook"}): ${Object.entries(v.values).map(([c, p]) => `${c} = ${p}`).join("; ")}`),
    `Then replace the place where we currently decide this (for example a call to a language model) with decide(). When review is true, hand the case to a person instead of acting. The possible actions are: ${choices.map((c) => `${c} (${spec.act.choices[c]})`).join(", ")}.`,
    "Do not change the module itself; write tests for the bucketing function.",
  ].join("\n");
  return { code, agent };
}

function renderUseIt(t) {
  const name = decideState.exported ?? `${decideState.spec.name}.decision.mjs`;
  const { code, agent } = useItText(decideState.spec, name);
  const box = el("div", "useit");
  box.append(el("h3", "useit-title", t("useItTitle")));
  box.append(el("pre", "mono useit-code", code));
  box.append(el("p", "hint", t("useItAgent")));
  const words = el("pre", "useit-agent", agent);
  const copy = el("button", "ghost", t("useItCopy"));
  copy.addEventListener("click", async () => {
    try { await navigator.clipboard.writeText(agent); copy.textContent = t("useItCopied"); }
    catch { const r = document.createRange(); r.selectNodeContents(words); const sel = getSelection(); sel.removeAllRanges(); sel.addRange(r); }
  });
  box.append(words, copy);
  return box;
}

// Step 3: the gate. One situation at a time, and never what the model said about it.
function renderAsk(root, t, redraw) {
  const section = card(t("decAskTitle"), 3);
  section.append(el("p", "hint", t("decAskHint")));
  const sheet = decideState.sheet;
  if (!sheet) return section;

  const answered = sheet.anchors.filter((a) => a.choice || a.allow?.length).length;
  const question = sheet.anchors[decideState.at];
  section.append(el("p", "count", t("decAskCount", answered, sheet.anchors.length)));

  if (question) {
    const box = el("div", "situation");
    for (const [field, phrase] of Object.entries(question.situation)) {
      const line = el("div", "sit-line");
      line.append(el("span", "sit-field", field), el("span", "sit-phrase", phrase));
      box.append(line);
    }
    section.append(box);
    section.append(el("p", "ask-question", decideState.read?.text ? decideState.spec.question : ""));

    const choices = el("div", "choices");
    const picked = new Set(question.allow ?? (question.choice ? [question.choice] : []));
    for (const [name, phrase] of Object.entries(decideState.spec.act.choices)) {
      const button = el("button", picked.has(name) ? "choice on" : "choice");
      button.append(el("strong", null, name), el("span", null, phrase));
      button.addEventListener("click", () => {
        const next = new Set(picked);
        next.has(name) ? next.delete(name) : next.add(name);
        if (next.size === 0) { delete question.choice; delete question.allow; }
        else if (next.size === 1) { question.choice = [...next][0]; delete question.allow; }
        else { question.allow = [...next]; delete question.choice; }
        redraw();
      });
      choices.append(button);
    }
    section.append(choices);
    section.append(el("p", "hint", t("decAskMulti")));
    section.append(el("p", "hint keys", t("decAskKeys")));
  }

  const nav = el("div", "row");
  const back = el("button", "ghost", t("decBack"));
  back.disabled = decideState.at === 0;
  back.addEventListener("click", () => { decideState.at -= 1; redraw(); });
  const skip = el("button", "ghost", t("decSkip"));
  skip.addEventListener("click", () => { decideState.at = Math.min(decideState.at + 1, sheet.anchors.length - 1); redraw(); });
  const next = el("button", "primary", t("decNext"));
  next.disabled = decideState.at >= sheet.anchors.length - 1;
  next.addEventListener("click", () => { decideState.at += 1; redraw(); });
  nav.append(back, skip, next);
  section.append(nav);
  return section;
}

// Step 4: can this decision be delegated at all, and with the threshold where.
function renderVerdict(root, t, redraw) {
  const section = card(t("decVerdictTitle"), 4);
  const sheet = decideState.sheet;
  const answered = sheet ? sheet.anchors.filter((a) => a.choice || a.allow?.length).length : 0;
  section.append(el("p", "hint", t("decVerdictHint")));

  const bar = el("div", "row");
  const go = el("button", "primary", t("decCalibrate"));
  go.disabled = !sheet || answered < 5 || Boolean(decideState.busy);
  go.addEventListener("click", async () => {
    decideState.busy = "cal"; decideState.error = ""; redraw();
    try {
      decideState.calibration = await api("decision.calibrate", { spec: decideState.spec, fill: decideState.fill, anchors: decideState.sheet, rule: decideState.spec.rule ?? null });
    } catch (error) { decideState.error = String(error.message); }
    decideState.busy = ""; redraw();
  });
  bar.append(go);
  if (sheet && answered < 5) bar.append(el("span", "hint", t("decNeedFive", answered)));
  section.append(bar);

  const cal = decideState.calibration;
  if (cal) {
    // A fill with one certainty in it makes seven identical rungs. Drawing all seven would
    // offer a choice that is not there, so it collapses to the single row it really is.
    const flat = (cal.confidenceValues ?? 2) <= 1;
    const table = el("table", "sweep");
    const head = el("tr");
    for (const key of ["decThreshold", "decDecides", "decAnchorsAbove", "decAgree"]) head.append(el("th", null, t(key)));
    table.append(head);
    for (const rung of (flat ? cal.sweep.slice(0, 1) : cal.sweep)) {
      const tr = el("tr", rung.threshold === cal.calibratedThreshold ? "chosen" : null);
      tr.append(el("td", "mono", flat ? t("decAnyThreshold") : String(rung.threshold)));
      tr.append(el("td", null, `${rung.settled}/${cal.legal} = ${Math.round(100 * rung.settledShare)}%`));
      tr.append(el("td", null, String(rung.anchorsAbove)));
      tr.append(el("td", rung.clean ? "clean" : null, `${rung.held}/${rung.anchorsAbove}`));
      table.append(tr);
    }
    section.append(table);
    if (flat) section.append(el("p", "hint", t("decOneConfidence")));

    // "Too few" is still a refusal - nothing is exported on it - but it is not an accusation, and
    // the way out is to answer more, not to give up on the decision.
    const tooFew = cal.verdict === "do-not-delegate" && cal.why === "too-few";
    const verdict = el("div", `verdict ${tooFew ? "too-few" : cal.verdict}`);
    verdict.append(el("strong", null, tooFew ? t("decV_too_few") : t(`decV_${cal.verdict.replace(/-/g, "_")}`)));
    verdict.append(el("p", null, tooFew
      ? (cal.agreesUpTo ? t("decVtooFewWhy", cal.agreesUpTo.held, cal.agreesUpTo.anchorsAbove, cal.agreesUpTo.threshold, cal.least) : t("decVtooFewNone", cal.least))
      : cal.verdict === "do-not-delegate"
      ? (flat ? t("decVdontWhyFlat", cal.sweep[0].anchorsAbove - cal.sweep[0].held, cal.sweep[0].anchorsAbove) : t("decVdontWhy"))
      : cal.verdict === "write-the-rule-instead"
        ? t("decVruleWhy", Math.round(100 * (cal.rule?.share ?? 0)))
        : t("decVdoWhy", cal.calibratedThreshold, Math.round(100 * (cal.decides ?? 0)))));
    section.append(verdict);

    if (cal.verdict !== "do-not-delegate") {
      const download = el("button", "primary", t("decExport"));
      download.addEventListener("click", async () => {
        try {
          const out = await api("decision.export", { spec: decideState.spec, fill: decideState.fill, anchors: decideState.sheet, calibration: cal });
          const url = URL.createObjectURL(new Blob([out.text], { type: "text/javascript" }));
          const a = document.createElement("a");
          a.href = url; a.download = out.name; a.click();
          URL.revokeObjectURL(url);
          decideState.exported = out.name;
          redraw();
        } catch (error) { decideState.error = String(error.message); redraw(); }
      });
      section.append(download);
      section.append(el("p", "hint", t("decExportHint")));
      section.append(renderUseIt(t));
    } else {
      section.append(el("p", "warn", tooFew ? t("decNoExportYet") : t("decNoExport")));
    }
  }
  return section;
}

// Twenty questions by mouse is forty clicks. A digit picks that option and moves on, which is
// how people actually get through a survey; shift+digit adds a second defensible option without
// moving, arrows walk back and forth. Typing in the codebook box is never intercepted.
let keyTarget = null;
function onKey(event) {
  if (!keyTarget || event.metaKey || event.ctrlKey || event.altKey) return;
  const { root, t } = keyTarget;
  if (root.hidden || !decideState.sheet || !decideState.spec) return;
  if (/^(INPUT|TEXTAREA|SELECT)$/.test(event.target?.tagName ?? "") || event.target?.isContentEditable) return;
  const anchors = decideState.sheet.anchors;
  const question = anchors[decideState.at];
  const names = Object.keys(decideState.spec.act.choices);
  const digit = /^Digit([1-9])$/.exec(event.code);
  if (digit && question && Number(digit[1]) <= names.length) {
    const name = names[Number(digit[1]) - 1];
    if (event.shiftKey) {
      const set = new Set(question.allow ?? (question.choice ? [question.choice] : []));
      set.has(name) ? set.delete(name) : set.add(name);
      delete question.choice; delete question.allow;
      if (set.size === 1) question.choice = [...set][0];
      else if (set.size > 1) question.allow = [...set];
    } else {
      question.choice = name;
      delete question.allow;
      decideState.at = Math.min(decideState.at + 1, anchors.length - 1);
    }
  } else if (event.key === "ArrowRight") decideState.at = Math.min(decideState.at + 1, anchors.length - 1);
  else if (event.key === "ArrowLeft") decideState.at = Math.max(decideState.at - 1, 0);
  else return;
  event.preventDefault();
  renderDecide(root, t);
}

export function renderDecide(root, t) {
  root.replaceChildren();
  const redraw = () => renderDecide(root, t);
  if (!keyTarget) {
    document.addEventListener("keydown", onKey);
    // Someone who went to a terminal to save the key comes back to this tab; notice it then.
    window.addEventListener("focus", () => { if (keyTarget && !keyTarget.root.hidden) probeKey().then(redrawDecide, () => {}); });
  }
  keyTarget = { root, t };
  persist();
  if (decideState.read) {
    const bar = el("div", "row restart");
    const again = el("button", "ghost", t("decStartOver"));
    again.addEventListener("click", () => { forgetDecision(); redraw(); });
    bar.append(el("span", "hint", t("decKept")), again);
    root.append(bar);
  }
  if (!decideState.read) root.append(renderLanding(t, { draw: drawCircuit, onTour: () => tourFor(t).start(), onOwn: startOwn }));
  root.append(renderSpec(root, t, () => renderDecide(root, t)));
  if (decideState.read) root.append(renderFill(root, t, () => renderDecide(root, t)));
  if (decideState.sheet) root.append(renderAsk(root, t, () => renderDecide(root, t)));
  if (decideState.sheet) root.append(renderVerdict(root, t, () => renderDecide(root, t)));
  if (decideState.error) root.append(el("p", "warn", decideState.error));
  tour?.refocus();
}

export async function probeKey() {
  try {
    decideState.hosted = !(await hasServer());
    const health = await api("health.status");
    decideState.keyPresent = health.decisionKey === "present";
    // No key of their own: ask how many of the free fills this address has left, so the page
    // can offer one instead of a dead button.
    decideState.trial = decideState.keyPresent ? null : await api("decision.trial").catch(() => null);
  } catch { decideState.keyPresent = null; }
}
