// Every word the browser UI shows, in English and Chinese. Both languages must
// carry the same keys (tests/ui.test.mjs checks).
export const STRINGS = {
  en: {
    decSwitch: "Decision",
    footerSite: "Runs in your browser. What you type stays here; the page connects out only to the model provider you choose, with your own key, and to the free-fill service when you use a free fill. No wallet, no private keys, no transactions.",
    landTitle1: "Freeze one decision.",
    landTitle2: "Prove it on every input.",
    landSub: "Your program makes the same small call again and again — approve or hold, keep or remove, retry or give up — and asks a model every time. gatecraft asks once for every situation, compiles the answers into a circuit proven on every input, has you check it, and hands you a 4 KB file to import.",
    landTour: "Take the 2-minute tour",
    landOwn: "Start with my own decision",
    landFree: "Runs in your browser. No sign-up, no key needed to try.",
    landDemoAnswers: "It answers",
    landDemoActs: "and acts on it",
    landDemoReview: "and hands it to a person",
    landDemoNext: "Another situation →",
    landDemoProof: (nand, rows) => `${nand} NAND gates · proven on ${rows}/${rows} inputs · running here`,
    landDemoFailed: "The demo circuit could not be loaded.",
    landNoPhrase: (code) => `code ${code} — no meaning given`,
    landHowTitle: "How it works",
    landHow1T: "Describe it",
    landHow1: "What the decision looks at, as a few categories, and the choices it can make.",
    landHow1D: "a codebook, ≤ 16 bits",
    landHow2T: "Fill it",
    landHow2: "Every situation gets an answer — from a rule, your own model, or a free fill.",
    landHow2D: "108 situations ≈ 8 s",
    landHow3T: "Prove it",
    landHow3: "The answers become NAND gates, checked on every input, then again by Yosys.",
    landHow3D: "256 / 256 inputs",
    landHow4T: "Check it",
    landHow4: "You answer twenty situations without seeing the model's answers. That decides whether to hand it over.",
    landHow4D: "20 blind questions",
    landHow5T: "Ship it",
    landHow5: "One file with no dependencies. import { decide } and call it with your program's codes.",
    landHow5D: "≈ 4 KB",
    landFitTitle: "Is it for you?",
    landFitYes: "A good fit",
    landFitYes1: "The same small decision runs many times a day.",
    landFitYes2: "What it looks at is already a few categories: a tier, a status, a bucketed number.",
    landFitYes3: "You can name the two to four things it can do.",
    landFitYes4: "Being wrong one way is worse than the other, so there is a safe choice.",
    landFitNo: "Not a fit",
    landFitNo1: "It has to read text, recognise a person, check the time or call another service.",
    landFitNo2: "The policy changes every week.",
    landFitNo3: "It looks at so much that nobody could spot-check twenty cases of it.",
    landHonest: "Every claim here was measured, including the ones that went against it.",
    landHonestLink: "What was tested, and what wasn't →",
    tourCount: (i, n) => `${i} of ${n}`,
    tourClose: "Close the tour",
    tourBack: "Back",
    tourNext: "Next",
    tourDone: "Finish",
    tourWorking: "Working…",
    tourDemoT: "This is a decision, running",
    tourDemo: "A forum decides what to do with a comment: keep it, fold it, or take it down. Here that decision is 32 NAND gates in your browser. Each situation lights the wires differently and gets an answer — and a code with no meaning is handed to a person automatically.",
    tourCodebookT: "1 · Describe the decision",
    tourCodebook: "This file is the decision. Each field is something your program already knows, as a small code (tone 0–2, target 0–2, …), each code with a plain-language meaning. A code with no meaning is illegal and always goes to a person.",
    tourReadT: "2 · It reads it back",
    tourRead: "gatecraft checks the file and says, in plain words, what to look at before spending anything: fields that would need to read text or look up a person, and whether the 'safe' choice is really the least damaging one.",
    tourFillT: "3 · Every situation is answered, then proven",
    tourFill: "All 108 legal situations got an answer — here from the example's own rule, so no key and no cost. The table then became 32 NAND gates, checked against the table on all 256 inputs.",
    tourTryT: "4 · Poke it",
    tourTry: "This runs the proven circuit itself. Change any code and watch the answer and the lit wires change. Try a code marked 'no phrase': it falls to the safe answer and hands the case to a person.",
    tourAskT: "5 · You check it — blind",
    tourAsk: "Proof only says the circuit matches the table. Whether the table is what you want, only you can say: answer twenty situations without seeing the model's answers. Keys 1, 2, 3 answer and move on.",
    tourVerdictT: "6 · The verdict",
    tourVerdict: "Your answers decide one of three outcomes: hand it over at a confidence threshold, write a plain if-statement instead, or do not hand it over at all. Then download one 4 KB file and import it.",
    tourYoursT: "Now yours",
    tourYours: "Describe your own decision in one sentence and let your own model draft the file — or paste one. No key? You get three free fills, or use your own model or a rule.",
    decFillByRule: "Or fill it from the rule in this file — no key",
    decFilledByRule: "Filled from the rule this file already states, so no model was asked and nothing was spent. Everything after this is real: the proof, the circuit you can poke, the twenty questions. One thing is not: a rule answers every situation with the same certainty, so the threshold at the end has nothing to sort. What the last step still tells you is whether your own twenty answers agree with the rule at all.",
    decOneConfidence: "Every row carries the same certainty, so the threshold has nothing to sort - 0.9 and 0.3 give the same table. The seven rungs are one rung.",
    decAnyThreshold: "any",
    decV_too_few: "Not settled yet - answer more.",
    decVtooFewWhy: (held, of, threshold, least) => `Where it acts it agrees with you - ${held} of ${of} at threshold ${threshold} - but ${least} answers above a threshold is the least that counts as evidence, and no threshold has that many yet. Answer more of the twenty and work it out again. Nothing is wrong yet; nothing is shown yet either.`,
    decVtooFewNone: (least) => `None of your answers fall where it would act, and ${least} is the least that counts as evidence. Answer more of the twenty and work it out again.`,
    decNoExportYet: "Nothing is exported until there is enough evidence either way.",
    decVdontWhyFlat: (broken, of) => `It acts on every situation, and ${broken} of your ${of} answers contradict what it does. Nothing here carries less certainty than anything else, so there is no threshold to retreat to: either the rule is wrong, or this decision belongs to people.`,
    decFilledByModel: "Filled by the decision model, one call per legal situation, with the key on this machine.",
    decNotesTitle: (n) => `${n} thing${n === 1 ? "" : "s"} to look at before you spend anything:`,
    decDraftOr: "Or say it in one sentence - what your program decides, what it can already see, what it can do - and let your own model draft the codebook:",
    decDraftPlaceholder: "e.g. Whether to auto-approve an expense claim, from its amount band, the submitter's tier, the category and whether a receipt is attached: approve, send to a manager, or reject.",
    decDraftGo: "Draft it with my model",
    decDrafting: "Drafting… (up to a minute)",
    decDraftPick: "Choose a model",
    decDraftModel: (label) => `Uses your own model: ${label}. It drafts; it does not judge. The read-back is where you check it.`,
    decDraftNoModel: "No model set up yet - choose one, or start from an example.",
    decDraftEmpty: "Write the sentence first.",
    decDraftFailed: (why) => `Two drafts in a row were not a legal decision (${why}). Say it differently, or start from an example.`,
    decDraftUnreachable: (origin, why) => `Could not reach ${origin} (${why}). Some providers do not accept requests from a browser page.`,
    decWidened: (field, from, to) => `The draft gave "${field}" ${from ?? "no"} bit${from === 1 ? "" : "s"}, which its own codes do not fit in, so it was widened to ${to}. That is arithmetic, not a judgement: the extra codes have no phrase and review by construction.`,
    decFillOwn: (calls) => `Ask my own model (${calls} calls)`,
    decOwnProgress: (done, total) => `Asking… ${done} / ${total}`,
    decOwnHint: (label, calls) => `No key for the decision model? Your own model can fill it: ${label}, straight from this page to your provider, each situation asked three times - ${calls} calls on your own account. How often the three agree becomes the confidence; a chat model's own confidence was measured to carry nothing.`,
    decOwnNoModel: "Or fill it with your own model - choose one at the top of the page first.",
    decOwnTooMany: (legal, max) => `${legal} situations is too many to ask your own model from a browser tab (the limit is ${max}); use the command line, or narrow the codebook.`,
    decOwnNothing: (why) => `Your model did not give a usable answer to any situation${why ? ` (${why})` : ""}. Try a larger model, or fill by rule.`,
    decFilledByOwn: (asks) => `Filled by your own model, each situation asked ${asks} times; the confidence is how often the answers agreed. A row is acted on only when they all did.`,
    decFillTrial: (left) => `Fill and freeze - free (${left} left)`,
    decTrialOffer: (left, limit) => `No decision-model key on this machine, so this uses one of ${limit} free fills for your address (${left} left) - same model, paid by the project. After that, fill with your own model below, or save a free key from typesafe.ai to ~/.config/gatecraft/jev.token.`,
    decTrialGone: (limit) => `The ${limit} free fills for your address are used. Fill with your own model below, from a rule if the file has one, or save a free key from typesafe.ai to ~/.config/gatecraft/jev.token.`,
    decTrialUsed: (left, limit) => `That used a free fill: ${left} of ${limit} left for your address. Bring your own model or key for the rest - it is the same flow, on your own account.`,
    decTryTitle: "Try it",
    decCircuitTitle: (n) => `The proven circuit · ${n} NAND`,
    decCircuitLit: "Lit wires carry 1 for the situation above. Change a code and watch it re-decide.",
    decCircuitTooBig: "This circuit is too large to draw legibly; the answer above still comes from running it.",
    decTryHint: "This runs the netlist that was just proven, here in the page. Not the table it was built from, and nothing is asked of any model.",
    decTryNoPhrase: (code) => `code ${code} · no phrase`,
    decTryAnswer: "It answers",
    decTryReview: "and hands it to a person",
    decTryActs: "and acts on it",
    decTryIllegalRow: (field) => `That ${field} code has no phrase in the codebook, so this situation is illegal. The safe action with review set is not a judgement anyone made - it falls out of the table's construction.`,
    decToFlow: "One sentence → one circuit",
    decExamples: "Never written one? Start from a decision that has actually been measured:",
    decEx_commentHold: "Hold a comment - 108 situations, keep / fold / remove",
    decEx_refundCall: "Answer a refund request - 108 situations, deny / partial / refund",
    decExFailed: "That example could not be loaded from this server.",
    decSpecTitle: "The decision, as a codebook",
    decSpecHint: "Paste a decision file. Every observed field gets a width and a phrase for each legal code - a code with no phrase is illegal, and the circuit answers those with the safe action and review = 1, by construction.",
    decSpecPlaceholder: "{ \"name\": \"...\", \"question\": \"...\", \"observe\": { ... }, \"act\": { \"choices\": { ... }, \"safe\": \"...\" } }",
    decRead: "Read it back to me",
    decFillTitle: "Answer every situation, then prove it",
    decFillHint: "Every legal situation is answered once, and the answers become the table. The decision model answers them with the key on this machine, which the page never sees; a file that states a rule can answer them itself, with no key at all.",
    decNoKey: "No decision-model key on this machine. One signup at typesafe.ai, then write it to ~/.config/gatecraft/jev.token",
    decFill: "Fill and freeze",
    decFilling: "Asking...",
    decFilled: (answered, settled, legal) => `${answered} of ${legal} situations answered; the model is sure enough about ${settled} of them.`,
    decFilledRule: (answered, legal) => `${answered} of ${legal} situations answered, every one of them exactly - a rule has nothing to be unsure about.`,
    decFrozen: (nand, rows, review) => `${nand} NAND, proven on all ${rows} rows. ${review} rows go to a person.`,
    decProofNotPolicy: "The proof relates the circuit to the table. It says nothing about whether the table is the policy you want - only the questions below bear on that.",
    decAskTitle: "Twenty situations, for you",
    decAskHint: "What the model answered is deliberately not shown: told that, you would be agreeing with the machine rather than judging. Of six decisions checked this way, two were ones where the model disagreed with the blind answers exactly where it was most confident - and nothing else here detects that.",
    decAskCount: (done, total) => `${done} of ${total} answered`,
    decAskMulti: "Pick more than one when more than one is defensible. Pick none to skip a case you would genuinely argue about - a blank is skipped, never counted as agreement.",
    decAskKeys: "Keys: 1, 2, 3 answer and move on · shift + a number adds a second defensible answer · ← → walk.",
    decStartOver: "Start over",
    decKept: "Your work here is kept in this browser, so a reload does not lose your answers.",
    decBack: "Back",
    decSkip: "Skip",
    decNext: "Next",
    decVerdictTitle: "Can this be delegated at all?",
    decVerdictHint: "The threshold is swept against your answers. The lowest one whose acted-on rows all still agree with you is the one to use.",
    decCalibrate: "Work out the threshold",
    decNeedFive: (n) => `${n} answered; five is the least that says anything.`,
    decThreshold: "threshold",
    decDecides: "it decides",
    decAnchorsAbove: "your answers above it",
    decAgree: "agree",
    decV_delegate: "Delegate it.",
    decV_write_the_rule_instead: "Write the rule instead.",
    decV_do_not_delegate: "Do not delegate this decision.",
    decVdoWhy: (threshold, percent) => `With the threshold at ${threshold} it settles ${percent}% of situations and hands the rest to a person, and every situation it would act on agrees with your answers.`,
    decVruleWhy: (percent) => `It is safe, but a written rule already matches ${percent}% of what it would decide. An if-statement is cheaper than a circuit.`,
    decVdontWhy: "At no threshold do the situations it would act on all agree with you. It is wrong where it is most confident, which no proof, repeat or confidence score detects.",
    decExport: "Download the module",
    decExportHint: "One file, no dependencies, no network: import { decide } from it and call it with the codes your program already has.",
    decNoExport: "There is nothing safe to export. Change the codebook, fill it differently, or leave this decision to people.",
    tagline: "One small decision out of your program, frozen into a table proven on every row.",
    footer: "Runs on this computer. The page loads files only from this local server. It connects elsewhere only when you ask: to the RPC you enter for a tape-out plan, and to the model provider you choose, with your own key. No wallet, no private keys, no transactions sent.",
    stepDescribe: "Describe the behaviour",
    stepProve: "Compile and prove",
    stepTry: "Try the circuit",
    stepTapeout: "Tape-out plan (unsigned)",

    gateNumber: (signal) => `gate ${signal}`,
    gateNand: (a, av, b, bv, value) => `This NAND gate: ${a} is ${av} and ${b} is ${bv}, so it outputs ${value}. A NAND outputs 0 only when both inputs are 1.`,
    gateLatch: (name, value, next) => `Memory ${name} holds ${value} right now, and becomes ${next} on the next clock tick.`,
    gateOutput: (name, value) => `Output ${name} is ${value}.`,
    gateInput: (name, value) => `Input ${name} is ${value}; flip it above.`,
    gateConst: (value) => `A fixed ${value}.`,
    gatePickHint: "Click any gate in the picture to see what it is computing right now.",
    waveTitle: "The next eight ticks",
    waveHint: "from the state above, with the inputs held",
    waveName: "value",
    toGallery: "Gallery",
    galleryTitle: "Things you can make, and things you made",
    galleryLead: "Every card here is a working app: the shape is compiled, proven on every input, and shown running. Nothing leaves this computer.",
    galleryPreview: "See it running",
    galleryBuilding: "Building…",
    galleryOpen: "Open it",
    galleryProven: (rows, nand) => `${rows} cases proven · ${nand} NAND`,
    templatesTitle: "Or start from a shape",
    templatesNote: "Pick one, turn its knobs, and the program is written for you — no model and no key. The compiler proves it on every input just the same.",
    templateBack: "All shapes",
    templateBuild: "Make this one →",
    flowFromTemplate: "Built from a template; turn its knobs again any time.",
    historyTitle: "Built here before",
    historyHint: (hash) => `Open it again and rebuild it byte for byte (netlist ${hash}…).`,
    historyMore: (n) => `and ${n} more`,
    historyClear: "Forget them",
    historyOpened: (name) => `${name} is back, with the seed and steps it had. Build it again to get the same bytes.`,
    flowFromHistory: "A circuit this browser built before; its program is back in the editor.",
    localModelFound: (name, model) => `Found ${name} on this computer with ${model}: a new sentence needs no key.`,
    buildStamp: (compiler) => `· ${compiler}`,
    apiPill: (n) => `API · ${n} methods`,
    apiPillHint: (compiler) => `This address also answers a local API for other programs on this machine (POST /api, ${compiler}). Click to see what it answers.`,
    stepsLabel: "Steps",
    flowStep_say: "Say it",
    flowStep_understand: "Check",
    flowStep_proof: "Prove",
    flowStep_try: "Try",
    reachTest: "Can this browser reach it?",
    reachTesting: "asking…",
    reachUnknown: "not tried yet",
    reachOk: (status) => `it answered (${status}); asking from this page works`,
    reachBlocked: (why) => `no answer from this page (${why}). Use the copied prompt, or a model on this computer.`,
    modelLocal: "local model",
    modelKeySet: "your key",
    modelNoKey: "no key yet",
    toWorkbench: "Workbench",
    toFlow: "Back to the sentence",
    settingsModelTitle: "Whose model",
    close: "Close",
    flowNeedSentence: "What should the circuit do? Write one sentence, or pick one on the right.",
    flowHeadline1: "Say it in one sentence.",
    flowHeadline2: "Get a circuit proven on every input.",
    flowLead: "The workbench, for a behaviour that is already small enough to be one circuit: a vote, a counter, a comparison, a switch. Of 300 things real people asked for, 3% were this small - if yours is one decision inside a larger program, it goes through Decision instead.",
    flowQuestion: "What should this circuit do?",
    modelAsksShort: "The model asks first:",
    flowAsk: "Understand this sentence →",
    flowAskHint: "About 20 seconds, on your own model. The four on the right need no key.",
    flowTryOne: "Not sure what to say? Pick one",
    flowHint_vote: "The simplest: 6 gates",
    flowHint_counter: "A circuit that remembers",
    flowHint_max: "Comparing numbers",
    flowHint_toggle: "Press to switch",
    exampleHolds: "holds",
    exampleFails: "does not hold",
    flowYouSaid: "You said",
    flowNoSentence: "(no sentence yet)",
    flowFromExample: "A ready-made program for this sentence; no model was called.",
    flowFromModel: "Your model wrote this program. Read it before you build.",
    hideProgram: "Hide the program",
    showProgram: "Show the program (advanced)",
    editInWorkbench: "Edit it in the workbench",
    flowCheckTitle: "Check it with examples",
    flowExamplesBad: (n) => `${n} does not match`,
    flowExamplesOk: (n) => `all ${n} hold`,
    flowFailingHelp: "An example does not match. Either the example is wrong (remove it) or the sentence was not clear (go back and change it). Nothing is built until they agree.",
    flowCheckNote: "Add a case you know the answer to. Every example is run on the program first; one that does not match stops the build.",
    flowBuild: "Yes, that is what I mean. Build it →",
    flowRephrase: "No, change the sentence",
    flowBuilding: "Building the circuit and checking every input…",
    flowNothingYet: "Nothing has been built yet.",
    flowBackToCheck: "Back to the check",
    flowProven: "Built, and proven",
    flowProofWords: (n) => `All ${n} possible inputs were run on the circuit, and every answer matches the program.`,
    flowProofWordsState: (n) => `All ${n} combinations of input and memory were run on the circuit, and every answer and next state matches the program.`,
    tileNand: "NAND gates",
    tileLatch: "memory cells (LATCH)",
    tileExamples: "examples hold",
    flowTryIt: "Try it →",
    flowLooksLike: "What it looks like",
    flowThumbNote: "Inputs on the left, outputs on the right; each D shape is one NAND gate. Try it to watch it work.",
    appTitle: "Turn it into an app",
    appSize: (kb) => `one file, ${kb} KB`,
    appNote: "One self-contained page: the circuit inside it, controls named after your sentence, and the proof printed on it. It opens by double-clicking, works with no network, and can be sent to anyone.",
    appDownload: "Download the app",
    appPreview: "Preview it here",
    appPreviewTitle: "The exported app",
    flowTakeIt: "Take it with you",
    file_circuit_netlist_json: "Circuit file",
    file_circuit_certificate_json: "Proof certificate",
    file_table_json: "Full truth table",
    chainTitle: "Already taped out? Check it against the chain",
    chainNote: "A taped-out circuit can be run on chain. This reads it and compares the chain's own answers with this circuit's, row by row. It only reads: no wallet, no signature, nothing spent.",
    chainContract: "Circuits contract",
    chainCheck: "Check against the chain",
    chainChecking: "reading the chain…",
    chainAgrees: (rows, total) => `the chain answers the same on ${rows} sampled rows (of ${total}).`,
    chainDisagrees: (wrong, rows) => `${wrong} of ${rows} sampled rows differ. Something is not the circuit you think it is.`,
    chainSameCircuit: "It is this exact netlist.",
    chainOtherCircuit: (nand) => `That id holds a different netlist (${nand} NAND).`,
    flowChipTitle: "Make it a real chip?",
    flowChipNote: "Hand the circuit to a fab and let it do the burning. This one file carries the netlist and its pin counts, so nothing is typed by hand; gatecraft never touches a wallet or sends a transaction.",
    flowChipDownload: "Download the import file",
    flowChipCopy: "Copy it instead",
    flowChipOpen: "Open the Firsto tape-out flow ↗",
    flowChipStep1: "Download the file (or copy it).",
    flowChipStep2: "Import it there: it reads the pin counts and the gate count straight out of the file.",
    flowChipStep3: "Connect your wallet there and tape out. The money and the transaction are yours, not ours.",
    flowChipOther: "Another fab, or the plan yourself",
    flowChipBlifNote: "A BLIF netlist is the generic format: tapeout.net's canvas imports it, and so do Yosys, ABC and SIS. It costs more gates there, though: a BLIF reader re-materialises this circuit's inverters and output buffers as gates of their own (the counter above goes from 35 to 47), so prefer the import file when the fab takes one.",
    flowChipCopyBlif: "Copy the BLIF",
    flowChipManual: "Or build the unsigned plan yourself (advanced)",
    flowChipManualNote: "The workbench reads the chain you name and writes the transactions for you to check and sign, without a wallet. Longer, and only needed if you are not using a fab's own flow.",
    flowChipButton: "Unsigned tape-out plan",
    file_circuit_blif: "Netlist for a fab (BLIF)",
    file_app_html: "The app (one page)",
    file_circuit_firsto_json: "Import file for the fab",
    sizeNand: (n) => `${n} NAND gates`,
    sizeWithLatch: (n, l) => `${n} NAND gates · ${l} memory cells`,
    flowTick: "Clock tick",
    flowTryTitle: "Flip the inputs and watch the circuit answer",
    flowTrySub: "This runs the circuit that would become the chip, gate by gate, not the program.",
    flowLiveTitle: "Inside the circuit right now",
    flowLiveCaption: "Lit wires carry 1",
    flowLiveCaptionState: "Lit wires carry 1; dashed wires carry the next state back into memory",
    flowAgrees: "The circuit's answer matches the program.",
    flowYourSentence: "Your sentence",
    flowHowToRead: "How to read the picture",
    legendNand: "A NAND gate. The whole circuit uses only this one kind: it outputs 0 only when both inputs are 1.",
    legendLatch: "A memory cell (LATCH). It keeps one bit and updates on the clock tick.",
    legendWire: "A lit wire carries 1 right now; a grey one carries 0.",
    flowStartOver: "Say something new",
    modelAsks: "The model needs to know more; add it to your sentence and ask again:",
    provider: "Provider",
    modelName: "Model",
    modelRequired: "required",
    apiAddress: "API address",
    apiKey: "API key",
    apiKeyPlaceholder: "your key; billed to your account",
    rememberKey: "Remember the key in this browser",
    byokNote: "The sentence and the key go only to the provider above, from this browser; gatecraft has no server and never sees them. Without the tick the key is forgotten when the page closes. An OpenAI-compatible address can be a local model server (http://127.0.0.1:…). If the program the model writes is rejected, it is shown the error and asked once more.",
    askModel: "Ask the model",
    asking: "Asking…",
    askingAttempt: (n) => (n === 1 ? "Waiting for the model…" : `The first program was rejected; asking again (try ${n})…`),
    gateChecking: "Checking whether a circuit can hold this at all…",
    gateRestart: (n, k) => `Starting over from a blank page (${n} of ${k})…`,
    gateNoTitle: "A circuit cannot do this one",
    gateAskTitle: "One thing is missing",
    gateAnswer: "Your answer",
    gateSend: "Use this and carry on",
    gateSkip: "Skip the check and try anyway",
    forkLooking: "Looking for a ready-made shape that fits…",
    forkPicked: (title) => `This looks like “${title}”. Read it over — if it is not what you meant, say so.`,
    forkNotIt: "Not this one — write it from scratch",
    playTitle: "Press it a few times",
    playNever: "Pressing this changes nothing at all — that is usually a misunderstanding somewhere",
    swapOffer: (rest) => (rest > 1 ? `One of the ${rest} things blocking it can be swapped — the others would still need dealing with:` : "There is a way round it:"),
    askedOk: (n) => (n === 1 ? "The model wrote this program. Read it before compiling." : `The model wrote this program on try ${n}. Read it before compiling.`),
    describeNote: "gatecraft pays for no model: you use your own, either with your API key below or by copying a prompt into the assistant you already use.",
    describePlaceholder: "e.g. Given two 6-bit numbers, output the larger one and whether they are equal.",
    makePrompt: "Write the prompt",
    copyPrompt: "Copy the prompt",
    describeEmpty: "Write a sentence first.",
    replyPlaceholder: "Paste the model's reply here",
    useReply: "Use this program",
    replyRejected: "The reply could not be used:",
    describeCheck: "The proof below shows the circuit matches the program, not that the program matches your sentence. Read the program and try a few inputs before you rely on it.",
    examplesTitle: "Examples: given these inputs, expect these outputs",
    examplePlaceholder: "a=3 b=5 -> larger=5   (with memory: press=1 count=9 -> then count=0)",
    addExample: "+ example",
    examplesHold: (n) => `${n} example${n === 1 ? "" : "s"} hold.`,
    examplesHoldProof: (n) => `All ${n} examples hold on the program, and the circuit matches the program on every row.`,
    readbackTitle: "What this program says, in words",
    noExamplesYet: "No examples yet. Add a few you know the answer to: they are checked before anything is compiled, and a wrong one stops the compile.",
    exprStates: "Memory (optional): values kept between clock ticks, 0 at power-on",
    nextIs: "bits, next =",
    addState: "+ memory",
    exprOkState: (nIn, nState, rows, nOut) => `${nIn} input bits and ${nState} memory bits, ${rows} combinations to check, ${nOut} output bits.`,
    tryNextState: "After the next tick",
    readyMade: "Ready-made, no key needed:",
    noKeyTitle: "No key? Copy a prompt into any chat assistant",
    needKey: "Your own model is needed for a new sentence: add your API key (or a model on this computer) in the model settings above, or copy the prompt into any chat assistant. The four sentences on the right need no key.",
    understandTitle: "What it understood",
    thenWord: "then memory:",
    kind_expr: "Expression",
    hint_expr: "The program under a sentence: named inputs and widths, memory, and one expression per output, with examples checked before anything is compiled.",
    fn_expr: "expression, e.g. a > b ? a - b : b - a",
    exprInputs: "Inputs",
    exprLets: "Shared definitions (optional)",
    exprOutputs: "Outputs",
    exprName: "name",
    exprWidth: "bits",
    addInput: "+ input",
    addLet: "+ definition",
    addOutput: "+ output",
    removeRow: "Remove",
    exprOk: (nIn, rows, nOut) => `${nIn} input bits, ${rows} rows to check, ${nOut} output bits.`,
    exprOkWide: (bits, max) => `${bits} bits of input and memory: more than one proof holds (${max}); it will be cut into blocks, each proven on its own.`,
    exprJson: "As JSON",
    exprJsonNote: "This JSON is the whole description: the command line takes it as it is, and it is the format a natural-language front end will write. Edit or paste one here.",
    applyJson: "Use this JSON",
    exprSemantics: "Values are exact integers with JavaScript's operators and precedence; each output is its value modulo 2^bits, so negative results wrap like hardware. Slices: a[3], a[7:4].",
    startsTitle: "Starting circuits, each checked on every row",
    frontEnd_bdd: "from the truth table (BDD)",
    frontEnd_expression: "from the expression's structure",
    startChosen: "annealed",
    startInexact: "wrong on some rows, dropped",
    kind_grid: "Decision grid",
    kind_table: "Truth table",
    kind_fsm: "State machine",
    hint_grid: "Two 4-bit inputs: X picks the row, Y the column. Paint what the circuit should choose for each of the 256 pairs.",
    hint_table: "Any function of up to 20 input bits. Click output bits, or fill the whole table from an expression in x.",
    hint_fsm: "For every state and input: what to output and which state comes next. The circuit powers on in state 0.",
    examples: "Examples:",
    expression: "Expression",
    fill: "Fill",
    fn_grid: "expression in x, y giving 0..3, e.g. x > y ? 1 : 2",
    fn_table: "expression in x, e.g. (x & 1) ^ (x >> 1 & 1)",
    fn_fsm: "expression in x, s returning [output, next state]",
    fillAll: "Paint every cell with the brush",
    choiceName: (k) => `Name of choice ${k}`,
    inputBits: "Input bits",
    outputBits: "Output bits",
    stateBits: "State bits",
    previewRows: (shown, total) => `Showing the first ${shown} of ${total} rows. Tables this large are edited through an expression.`,
    colInput: "input x",
    colState: "state",
    colOutput: "output",
    colNext: "next state",
    graphTooBig: "The state diagram is drawn for up to 8 states and 3 input bits.",
    graphLegend: "Arrow labels read input/output. The thick circle is the power-on state.",

    name: "Name",
    steps: "Annealing steps",
    seed: "Seed",
    auto: "auto",
    fromTable: "from the table",
    objective: "Optimise for",
    objective_gates: "fewest NAND",
    objective_cost: "lowest PoD cost",
    compile: "Compile and prove",
    cancel: "Cancel",
    phase_synthesis: "Synthesising NAND gates from a BDD…",
    phase_annealing: "Shrinking the circuit…",
    phase_verification: "Checking every row…",
    phase_block: "Proving block",
    badName: "Name must be a short lowercase slug, like my-circuit.",
    badSteps: "Steps must be a whole number from 1 to 1,000,000,000.",
    badSeed: "Seed must be an integer 0..4294967295 or 0x-prefixed hex.",
    workerFailed: "The compiler worker failed to start.",
    labelEmpty: "Every choice needs a name.",
    labelComma: "Choice names cannot contain commas.",
    labelDuplicate: "Choice names must all be different.",

    proofPlaceholder: "Compile to see the proof: gate count, depth, and every row checked.",
    stale: "The description has changed since this compile. Compile again to prove the new version.",
    provenRows: "rows checked against the circuit, none wrong",
    provenFsm: "(input, state) pairs checked: every output and next state matches",
    methods: (m) => `Checked by ${m}.`,
    depth: "depth",
    podCost: "PoD cost",
    bytes: "bytes",
    shrink: (a, b) => `The starting circuit had ${a} NAND; annealing brought it to ${b}.`,
    reachable: (a, b) => `${a} of ${b} states can be reached from power-on.`,
    tableShape: (i, o) => `${i} input bits, ${o} output bits.`,
    neverChosen: (list) => `Never chosen: ${list}.`,
    everyChoiceUsed: "Every choice occurs somewhere.",
    reproduce: "Reproduce",
    tableHash: "table SHA-256",
    netlistHash: "netlist SHA-256",
    variableOrder: "BDD variable order, top first",
    sifted: "improved by sifting",
    reproduceNote: "The same table, seed and steps give the same bytes on any machine. With the spec file downloaded, this command rebuilds it:",
    copy: "Copy",
    copied: "Copied",
    downloadSpec: "Spec for the command line",

    tryInputs: "Inputs",
    tryState: "State",
    tryOutputs: "Outputs",
    tick: "Clock tick",
    reset: "Reset to state 0",
    agrees: "Matches the table.",
    disagrees: "Does not match the table.",
    traceTitle: "Last ticks",
    tooBigToDraw: (n) => `${n} elements are too many to draw clearly. Download the netlist to inspect it.`,
    diagramAria: "Circuit diagram",
    diagramNote: "Highlighted wires carry 1. Dashed wires feed the latches for the next tick.",

    unsignedNotice: "gatecraft reads the chain and writes an unsigned plan. It never asks for a wallet or a private key and never sends a transaction. Check the plan, then sign the transactions yourself, in order.",
    rpc: "RPC URL",
    rpcHint: "Must accept requests from a browser (CORS). Otherwise use the command line.",
    processor: "Processor contract",
    fromAddr: "Your wallet address",
    fromHint: "Only used to read your NAND and LATCH balances.",
    chainId: "Chain ID",
    chainIdHint: "Refuse unless the RPC is on this chain. Leave empty to skip.",
    implementation: "Expected implementation",
    implementationHint: "Refuse unless the processor's EIP-1967 implementation is this address.",
    optional: "optional",
    buildPlan: "Read the chain and build the plan",
    reading: "Reading the chain…",
    badRpc: "The RPC URL must start with http:// or https://.",
    badChainId: "Chain ID must be a positive whole number.",
    rpcUnreachable: "The browser could not reach this RPC. It may not allow browser requests (CORS). The command line has no such limit:",
    block: "read at block",
    expectedId: "expected circuit id",
    balances: "your balances",
    fees: "fees",
    tapeoutFee: "tape-out",
    mintPrice: "mint price",
    protocolFee: "protocol fee",
    total: "total to send",
    guards: "checks passed",
    purpose: "purpose",
    to: "to",
    value: "value",
    data: "calldata",
    copyPlan: "Copy plan JSON",
    downloadPlan: "Download plan",
    idCaveat: "The expected circuit id holds only if nobody else tapes out on this processor before you.",
    nativeUnit: "native token",
    supplyLeft: "left to mint",
    simOk: (n, id, gas) => `Simulated on the block the plan was read at: all ${n} transactions succeed in order, the tapeout issues circuit ${id}, ${gas} gas in total.`,
    simToppedUp: "Your native balance is below the total value, so the simulation topped it up. Fund the wallet before signing.",
    simFailed: "Simulated on the block the plan was read at, these transactions would fail. Do not sign them.",
    simUnsupported: "This RPC does not support eth_simulateV1, so the plan was not simulated. Check it with care, or use an RPC that can simulate.",
    wideTitle: (bits) => `${bits} bits of input and state: more than one proof can hold`,
    wideBody: "It can still be built. Each rule becomes its own small circuit, proven on every row of its own table. How they are joined is your call, because it changes what gets deployed.",
    wideLinked: "Link them into one circuit (REF)",
    wideLinkedHint: "One circuit of latches and references, no logic of its own. Deploy the blocks, fill in their ids, and it runs as one on the chain. Identical blocks are deployed once.",
    wideReplay: "Keep them separate (replay)",
    wideReplayHint: "The blocks plus an order to run them in. Your caller holds the state and never uses REF.",
    composedBlocks: "blocks",
    bits: "bits",
    composedEvery: "every row",
    composedProven: (n) => `${n} block${n === 1 ? "" : "s"}, each checked on every row of its own table`,
    composedComputes: "Computes",
    composedReads: "Bits in → out",
    composedRows: "Rows exact",
    composedTop: (latch, refs) => `The top circuit is ${latch} latches and ${refs} references, with no NAND of its own: nothing can be wrong in the wiring that is not wrong in a block.`,
    composedEndToEnd: (rows, all) => `The linked circuit, the replay order and the program agree on ${rows} rows${all ? " (every one)" : " (the examples plus sampled rows; the block proofs are the guarantee, this checks the wiring)"}.`,
    composedInlined: (names) => `Kept inside the blocks that read them, because they can go negative: ${names}.`,
    composedNoSim: "The step-by-step run and the tapeout plan work on one circuit; for blocks, download the files below. Linking needs the blocks deployed first.",
    deliveryLinked: "Delivered linked: top.netlist.json refers to the blocks.",
    deliveryReplay: "Delivered separate: replay.json lists the blocks and their order.",
  },

  zh: {
    decSwitch: "决策",
    footerSite: "在你的浏览器里运行。你输入的内容都留在这里；页面只在两种情况下连外部：用你自己的 key 连你选的模型服务商，以及你使用免费填表时连免费填表服务。不连钱包，不碰私钥，不发送交易。",
    landTitle1: "把一个决策冻结下来，",
    landTitle2: "在每一种输入上证明它。",
    landSub: "你的程序反复做同一个小决定——批还是不批、留还是删、重试还是放弃——而且每次都去问模型。gatecraft 把每一种情况都提前问一次，把答案编译成一颗在每种输入上都证明过的电路，让你核对一遍，最后交给你一个 4 KB 的文件直接 import。",
    landTour: "两分钟导览",
    landOwn: "从我自己的决策开始",
    landFree: "在你的浏览器里运行。不用注册，不用 key 就能试。",
    landDemoAnswers: "它的回答",
    landDemoActs: "并且直接执行",
    landDemoReview: "并且交给人",
    landDemoNext: "换一种情况 →",
    landDemoProof: (nand, rows) => `${nand} 个与非门 · ${rows}/${rows} 种输入全部证明 · 正在这里运行`,
    landDemoFailed: "演示电路没能加载。",
    landNoPhrase: (code) => `编码 ${code}——没有定义含义`,
    landHowTitle: "它怎么工作",
    landHow1T: "描述它",
    landHow1: "这个决策要看哪几样东西（每样分成几档），以及它能做哪几种选择。",
    landHow1D: "一份 codebook，≤ 16 位",
    landHow2T: "填表",
    landHow2: "每一种情况都给出答案——用规则、用你自己的模型，或者用免费次数。",
    landHow2D: "108 种情况约 8 秒",
    landHow3T: "证明",
    landHow3: "答案变成与非门电路，在每一种输入上核对，再让 Yosys 独立证明一遍。",
    landHow3D: "256 / 256 种输入",
    landHow4T: "核对",
    landHow4: "你在看不到模型答案的情况下答二十道题，由此决定这个决策能不能交出去。",
    landHow4D: "二十道盲答",
    landHow5T: "交付",
    landHow5: "一个零依赖的文件。import { decide }，用你程序里现成的编码去调它。",
    landHow5D: "约 4 KB",
    landFitTitle: "适不适合你？",
    landFitYes: "适合",
    landFitYes1: "同一个小决策，每天要做很多次。",
    landFitYes2: "它要看的东西本来就是几档：等级、状态、分好桶的数字。",
    landFitYes3: "你说得出它能做的两到四种选择。",
    landFitYes4: "错向一边比错向另一边更糟，所以存在一个「安全」的选择。",
    landFitNo: "不适合",
    landFitNo1: "需要读文字、认人、看时间，或者调用别的服务。",
    landFitNo2: "规则每周都在变。",
    landFitNo3: "要看的东西太多，任何人都没法从中抽二十个来核对。",
    landHonest: "这里的每一条说法都实测过，包括对我们不利的那些。",
    landHonestLink: "测了什么、没测什么 →",
    tourCount: (i, n) => `${i} / ${n}`,
    tourClose: "关闭导览",
    tourBack: "上一步",
    tourNext: "下一步",
    tourDone: "完成",
    tourWorking: "处理中……",
    tourDemoT: "这是一个正在运行的决策",
    tourDemo: "一个论坛要决定怎么处理一条评论：保留、折叠，还是删除。这里这个决策就是你浏览器里的 32 个与非门。每一种情况会点亮不同的线、得出一个回答——而没有定义含义的编码，会自动交给人。",
    tourCodebookT: "1 · 描述这个决策",
    tourCodebook: "这份文件就是这个决策。每个字段都是你的程序本来就知道的东西，用一个小编码表示（语气 0–2、对象 0–2……），每个编码都配一句人话。没有配人话的编码就是非法的，永远交给人处理。",
    tourReadT: "2 · 它先读回给你听",
    tourRead: "gatecraft 检查这份文件，用人话告诉你花钱之前该看什么：哪些字段需要读文字或去查某个人，以及那个「安全」选项是不是真的损害最小。",
    tourFillT: "3 · 每种情况都答一遍，然后证明",
    tourFill: "108 种合法情况全部有了答案——这里用的是例子自带的规则，所以不用 key、不花钱。然后这张表变成了 32 个与非门，在全部 256 种输入上逐一核对过。",
    tourTryT: "4 · 上手点一点",
    tourTry: "这里跑的就是被证明的那颗电路本身。随便换一个编码，看回答和亮着的线怎么变。试试标着「没有人话」的编码：它会落到安全的回答上，并把这件事交给人。",
    tourAskT: "5 · 你来核对——盲答",
    tourAsk: "证明只说明电路和表一致。这张表是不是你想要的，只有你能判断：在看不到模型答案的情况下答二十道题。按 1、2、3 作答并自动跳到下一题。",
    tourVerdictT: "6 · 裁决",
    tourVerdict: "你的答案决定三种结果之一：在某个把握度门槛下交出去、改写成一个普通的 if、或者根本不交出去。然后下载一个 4 KB 的文件 import 进你的程序。",
    tourYoursT: "轮到你了",
    tourYours: "用一句话描述你自己的决策，让你自己的模型起草这份文件——或者直接贴一份。没有 key？你有三次免费填表，也可以用你自己的模型或者规则来填。",
    decFillByRule: "或者用文件里那条规则填 —— 不用 key",
    decFilledByRule: "用这份文件里已经写好的规则填的，没问任何模型，也没花钱。后面每一步都是真的：证明、能上手点的电路、二十道盲答。只有一件事不真：规则对每一种情况的把握度都一样，所以最后那个门槛没有东西可以分。最后一步仍然会告诉你一件事——你自己答的那二十道，到底同不同意这条规则。",
    decOneConfidence: "每一行的把握度都一样，所以门槛没有东西可以分——0.9 和 0.3 得到的是同一张表。七档其实只有一档。",
    decAnyThreshold: "任意",
    decV_too_few: "还定不下来——再多答几道。",
    decVtooFewWhy: (held, of, threshold, least) => `它会执行的地方和你是一致的——门槛 ${threshold} 时 ${of} 道里 ${held} 道一致——但门槛以上至少要有 ${least} 道答案才算证据，目前哪一档都还不够。把二十道再多答几道，然后重新算。现在既没有发现它错，也还不能说明它对。`,
    decVtooFewNone: (least) => `你答的题里没有一道落在它会执行的范围内，而至少要 ${least} 道才算证据。把二十道再多答几道，然后重新算。`,
    decNoExportYet: "证据够之前，什么都不导出。",
    decVdontWhyFlat: (broken, of) => `它对每一种情况都会直接执行，而你答的 ${of} 道里有 ${broken} 道和它相反。这里没有哪一行比别的行更没把握，所以没有门槛可退：要么这条规则是错的，要么这个决策本来就该留给人。`,
    decFilledByModel: "由决策模型填的，每一种合法情况问一次，用的是这台机器上的 key。",
    decNotesTitle: (n) => `花钱之前先看这 ${n} 条：`,
    decDraftOr: "或者用一句话说清楚——你的程序要决定什么、它手上已经有哪些信息、能做哪几种动作——让你自己的模型起草 codebook：",
    decDraftPlaceholder: "例如：一笔报销要不要自动通过，看金额档位、提交人级别、类别、有没有附发票；可以通过、转给经理、或者驳回。",
    decDraftGo: "用我的模型起草",
    decDrafting: "起草中……（最多一分钟左右）",
    decDraftPick: "选模型",
    decDraftModel: (label) => `用的是你自己的模型：${label}。它只负责起草，不负责判断——下面的读回才是你检查它的地方。`,
    decDraftNoModel: "还没配置模型——选一个，或者从例子开始。",
    decDraftEmpty: "先把那句话写上。",
    decDraftFailed: (why) => `连续两份草稿都不是合法的决策（${why}）。换个说法，或者从例子开始。`,
    decDraftUnreachable: (origin, why) => `连不上 ${origin}（${why}）。有些服务商不接受网页里直接发来的请求。`,
    decWidened: (field, from, to) => `草稿给「${field}」的是 ${from ?? "0"} 位，装不下它自己列出的编码，所以放宽到了 ${to} 位。这是算术，不是判断：多出来的编码没有人话，由表构造出来就是复审。`,
    decFillOwn: (calls) => `用我自己的模型填（${calls} 次调用）`,
    decOwnProgress: (done, total) => `正在问…… ${done} / ${total}`,
    decOwnHint: (label, calls) => `没有决策模型的 key？可以用你自己的模型填：${label}，从这个页面直接发给你的服务商，每种情况问三遍，一共 ${calls} 次调用，记在你自己的账上。三次答案一致的比例就是把握度——聊天模型自己报的把握度，实测没有信息量。`,
    decOwnNoModel: "也可以用你自己的模型填——先在页面顶部选一个模型。",
    decOwnTooMany: (legal, max) => `${legal} 种情况太多，不适合在浏览器里用你自己的模型问（上限 ${max}）；请用命令行，或者把 codebook 收窄一点。`,
    decOwnNothing: (why) => `你的模型一种情况都没有给出能用的答案${why ? `（${why}）` : ""}。换个大一点的模型，或者用规则填。`,
    decFilledByOwn: (asks) => `由你自己的模型填的，每种情况问了 ${asks} 遍；把握度就是答案一致的比例。只有全部一致的行才会直接执行。`,
    decFillTrial: (left) => `填表并冻结——免费（还剩 ${left} 次）`,
    decTrialOffer: (left, limit) => `这台机器上没有决策模型的 key，所以这次会用掉你这个地址的 ${limit} 次免费填表之一（还剩 ${left} 次）——同一个模型，项目方付费。之后请用下面「用我自己的模型填」，或者去 typesafe.ai 免费注册一个 key，存到 ~/.config/gatecraft/jev.token。`,
    decTrialGone: (limit) => `你这个地址的 ${limit} 次免费填表已经用完。请用下面「用我自己的模型填」，文件里有规则的话也可以用规则填，或者去 typesafe.ai 免费注册一个 key，存到 ~/.config/gatecraft/jev.token。`,
    decTrialUsed: (left, limit) => `刚才用掉了一次免费填表：你这个地址还剩 ${left} / ${limit} 次。之后请接你自己的模型或 key——流程完全一样，只是记在你自己的账上。`,
    decTryTitle: "试一下",
    decCircuitTitle: (n) => `被证明的那颗电路 · ${n} 个与非门`,
    decCircuitLit: "亮的线表示上面这个情况下它传的是 1。换一个编码，看它重新判一遍。",
    decCircuitTooBig: "这颗电路太大，画出来看不清；上面的答案照样是跑它得出的。",
    decTryHint: "这里跑的就是刚刚被证明过的那份电路网表，在页面里跑。不是它背后那张表，也不问任何模型。",
    decTryNoPhrase: (code) => `编码 ${code} · 没有人话`,
    decTryAnswer: "它的回答",
    decTryReview: "并且交给人",
    decTryActs: "并且直接执行",
    decTryIllegalRow: (field) => `${field} 的这个编码在 codebook 里没有配人话，所以这一行非法。安全动作 + 复审不是谁判断出来的，是这张表构造出来就是这样。`,
    decToFlow: "一句话变电路",
    decExamples: "没写过？从一个真的被测量过的决策开始：",
    decEx_commentHold: "一条评论要不要拦——108 种情况，保留／折叠／删除",
    decEx_refundCall: "一个退款请求怎么处理——108 种情况，拒绝／部分／全额",
    decExFailed: "这台服务器上取不到那个例子。",
    decSpecTitle: "把决策写成 codebook",
    decSpecHint: "贴一份决策文件。每个观测字段给位宽，每个合法编码配一句人话——没有人话的编码就是非法编码，电路对它们给安全动作 + 复审，这是由表构造出来的，不来自任何模型的判断。",
    decSpecPlaceholder: "{ \"name\": \"...\", \"question\": \"...\", \"observe\": { ... }, \"act\": { \"choices\": { ... }, \"safe\": \"...\" } }",
    decRead: "用人话读回来给我看",
    decFillTitle: "把每种情况都答一遍，然后证明它",
    decFillHint: "每一种合法情况都被答一次，答案就是那张表。问决策模型用的是这台机器上的 key，页面看不到它；如果文件里写了规则，也可以直接用规则答，完全不用 key。",
    decNoKey: "这台机器上没有决策模型的 key。去 typesafe.ai 注册一次，然后写进 ~/.config/gatecraft/jev.token",
    decFill: "填表并冻结",
    decFilling: "正在问……",
    decFilled: (answered, settled, legal) => `${legal} 种情况答上了 ${answered} 种；其中 ${settled} 种模型有足够把握。`,
    decFilledRule: (answered, legal) => `${legal} 种情况答上了 ${answered} 种，而且每一种都是确定的——规则没有「拿不准」这回事。`,
    decFrozen: (nand, rows, review) => `${nand} 个与非门，${rows} 行全部证明通过。${review} 行交给人。`,
    decProofNotPolicy: "证明关联的是「电路」和「这张表」。它不保证这张表就是你想要的政策——只有下面那些题能说明这件事。",
    decAskTitle: "二十种情况，问你",
    decAskHint: "模型的答案刻意不显示：看了它，你就是在附和机器而不是在判断。检查过的六个决策里，有两个是「模型在最有把握处也和盲答不一致」——而这里别的任何检查都发现不了。",
    decAskCount: (done, total) => `已答 ${done} / ${total}`,
    decAskMulti: "几个都说得过去就都选上。一个都不选表示跳过——空着会被跳过，绝不会被算成同意。",
    decAskKeys: "键盘：按 1、2、3 作答并跳到下一题 · shift + 数字再加一个也说得过去的答案 · ← → 前后翻。",
    decStartOver: "从头来",
    decKept: "这里做到哪儿都存在这个浏览器里，刷新不会丢掉你的答案。",
    decBack: "上一题",
    decSkip: "跳过",
    decNext: "下一题",
    decVerdictTitle: "这个决策到底能不能交给它？",
    decVerdictHint: "拿你的答案去扫门槛。最低的那个「会被执行的行仍然全部和你一致」的门槛，就是该用的。",
    decCalibrate: "算出门槛",
    decNeedFive: (n) => `已答 ${n} 题；至少要 5 题才说明得了问题。`,
    decThreshold: "门槛",
    decDecides: "它决定",
    decAnchorsAbove: "你的答案落在其上",
    decAgree: "一致",
    decV_delegate: "可以交给它。",
    decV_write_the_rule_instead: "写个规则更划算。",
    decV_do_not_delegate: "别把这个决策交给它。",
    decVdoWhy: (threshold, percent) => `门槛定在 ${threshold}，它能定下 ${percent}% 的情况、其余交给人，而且它会执行的每一种情况都和你的答案一致。`,
    decVruleWhy: (percent) => `它是安全的，但现成的规则已经能对上它 ${percent}% 的判断。写个 if 比造一颗电路便宜。`,
    decVdontWhy: "任何门槛下，它要执行的那些情况都没法全部和你一致。它在最有把握的地方也是错的——而这一点，证明、重跑、把握度都发现不了。",
    decExport: "下载模块",
    decExportHint: "一个文件、零依赖、不联网：import { decide } 进来，用你程序里已有的编码调它。",
    decNoExport: "没有可以安全导出的东西。改 codebook、换个填法，或者把这个决策留给人。",
    tagline: "把程序里的一个小决策抠出来，冻成一张逐行证明过的表。",
    footer: "全部在这台电脑上运行。页面只从本机服务器加载文件，只在你要求时才连接别处：生成流片单时读取你填写的 RPC，问模型时用你自己的 key 连你选的服务商。不连钱包，不碰私钥，不发送任何交易。",
    stepDescribe: "描述行为",
    stepProve: "编译并证明",
    stepTry: "试用电路",
    stepTapeout: "流片单（未签名）",

    gateNumber: (signal) => `第 ${signal} 号门`,
    gateNand: (a, av, b, bv, value) => `这个与非门：${a} 是 ${av}，${b} 是 ${bv}，所以它输出 ${value}。与非门只有两个输入都是 1 时才输出 0。`,
    gateLatch: (name, value, next) => `记忆 ${name} 此刻是 ${value}，下一拍会变成 ${next}。`,
    gateOutput: (name, value) => `输出 ${name} 是 ${value}。`,
    gateInput: (name, value) => `输入 ${name} 是 ${value}，在上面拨它。`,
    gateConst: (value) => `一个固定的 ${value}。`,
    gatePickHint: "点图里任意一个门，看它此刻在算什么。",
    waveTitle: "接下来八拍",
    waveHint: "从上面的状态开始，输入保持不变",
    waveName: "值",
    toGallery: "作品",
    galleryTitle: "能做的，和你做过的",
    galleryLead: "这里每一张卡片都是一个能用的应用：形状会被编译、在每一种输入上证明，然后当场跑给你看。东西不出这台电脑。",
    galleryPreview: "看它跑起来",
    galleryBuilding: "正在造…",
    galleryOpen: "打开它",
    galleryProven: (rows, nand) => `${rows} 种情况已证明 · ${nand} 个与非门`,
    templatesTitle: "或者从一个现成形状开始",
    templatesNote: "挑一个、调两个参数，程序就替你写好了 —— 不用模型，也不用 key。编译器照样在每一种输入上证明它。",
    templateBack: "全部形状",
    templateBuild: "就造这个 →",
    flowFromTemplate: "从模板造的，随时可以回去改参数。",
    historyTitle: "这里造过的",
    historyHint: (hash) => `重新打开并逐字节重造（网表 ${hash}…）。`,
    historyMore: (n) => `还有 ${n} 个`,
    historyClear: "忘掉它们",
    historyOpened: (name) => `${name} 回来了，种子和步数都是原来的。再造一次就是同样的字节。`,
    flowFromHistory: "这个浏览器以前造过的电路，程序已经放回编辑器。",
    localModelFound: (name, model) => `发现本机的 ${name}（模型 ${model}）：写新句子不用填 key。`,
    buildStamp: (compiler) => `· ${compiler}`,
    apiPill: (n) => `API · ${n} 个方法`,
    apiPillHint: (compiler) => `这个地址还答应一个本机 API，给这台机器上的其他程序用（POST /api，${compiler}）。点开看它答应哪些方法。`,
    stepsLabel: "步骤",
    flowStep_say: "说一句话",
    flowStep_understand: "核对",
    flowStep_proof: "证明",
    flowStep_try: "试用",
    reachTest: "测一下浏览器能不能直连",
    reachTesting: "正在问…",
    reachUnknown: "还没测过",
    reachOk: (status) => `它回话了（${status}），从这个页面直接问没问题`,
    reachBlocked: (why) => `这个页面连不上它（${why}）。用复制提示词，或者本机的模型。`,
    modelLocal: "本机模型",
    modelKeySet: "你的 key",
    modelNoKey: "还没填 key",
    toWorkbench: "工作台",
    toFlow: "回到一句话",
    settingsModelTitle: "用谁的模型",
    close: "关闭",
    flowNeedSentence: "你想让电路做什么？先写一句话，或者点右边的例子。",
    flowHeadline1: "说一句话，",
    flowHeadline2: "得到一颗被证明过的电路。",
    flowLead: "这是工作台，给本来就小到能做成一颗电路的行为：投票、计数、比大小、开关。实测 300 条真人随口许的愿望，只有 3% 有这么小——如果你要的是一个大程序里的某一个决策，走「决策」那边。",
    flowQuestion: "这颗电路要做什么？",
    modelAsksShort: "模型想先问清楚：",
    flowAsk: "让模型理解这句话 →",
    flowAskHint: "大约 20 秒，用你自己的模型。右边四句不用 key。",
    flowTryOne: "不知道说什么？点一句试试",
    flowHint_vote: "最简单的一句，6 个与非门",
    flowHint_counter: "会记东西的电路",
    flowHint_max: "比大小",
    flowHint_toggle: "按一下切换",
    exampleHolds: "成立",
    exampleFails: "不成立",
    flowYouSaid: "你说的是",
    flowNoSentence: "（还没有写句子）",
    flowFromExample: "这句话有现成的程序，没有调用模型。",
    flowFromModel: "这段程序是你的模型写的，造电路前先读一遍。",
    hideProgram: "收起程序",
    showProgram: "看看程序（高级）",
    editInWorkbench: "在工作台里改",
    flowCheckTitle: "拿例子核对一下",
    flowExamplesBad: (n) => `有 ${n} 个对不上`,
    flowExamplesOk: (n) => `${n} 个都对`,
    flowFailingHelp: "有例子对不上：要么例子写错了（删掉它），要么那句话没说清（回去改）。两边一致之前不会造电路。",
    flowCheckNote: "加一个你知道答案的例子。每个例子先在程序上算一遍，有一个对不上就不造电路。",
    flowBuild: "对，就是这个意思，造出电路 →",
    flowRephrase: "不对，改一下那句话",
    flowBuilding: "正在造电路，并逐一验证每一种输入…",
    flowNothingYet: "还没有造出电路。",
    flowBackToCheck: "回到核对",
    flowProven: "电路造好了，而且证明过",
    flowProofWords: (n) => `全部 ${n} 种输入都在电路上算过一遍，每一个结果都和程序一模一样。`,
    flowProofWordsState: (n) => `输入和记忆的全部 ${n} 种组合都在电路上算过一遍，每个输出和下一拍的状态都和程序一模一样。`,
    tileNand: "个与非门（NAND）",
    tileLatch: "个存储单元（LATCH）",
    tileExamples: "个例子全部成立",
    flowTryIt: "动手试一试 →",
    flowLooksLike: "电路长这样",
    flowThumbNote: "左边是输入，右边是输出，中间每个 D 形都是一个与非门。去试用里看它动起来。",
    appTitle: "变成一个应用",
    appSize: (kb) => `一个文件，${kb} KB`,
    appNote: "一个自带一切的网页：电路在里面，控件按你那句话命名，证明结果印在上面。双击就能打开，不联网，可以直接发给别人。",
    appDownload: "下载这个应用",
    appPreview: "在这里预览",
    appPreviewTitle: "导出的应用",
    flowTakeIt: "带走它",
    file_circuit_netlist_json: "电路文件",
    file_circuit_certificate_json: "证明书",
    file_table_json: "完整真值表",
    chainTitle: "已经流片了？和链上核对一下",
    chainNote: "流片过的电路能在链上被运行。这里读出它，让链上和你手里这颗逐行算同样的输入再对照。只读：不连钱包、不签名、不花钱。",
    chainContract: "电路合约地址",
    chainCheck: "和链上核对",
    chainChecking: "正在读链…",
    chainAgrees: (rows, total) => `抽样 ${rows} 行（共 ${total} 行），链上给的答案一模一样。`,
    chainDisagrees: (wrong, rows) => `抽样 ${rows} 行里有 ${wrong} 行不一样。那颗电路和你以为的不是同一个。`,
    chainSameCircuit: "而且就是这份网表。",
    chainOtherCircuit: (nand) => `这个编号上是另一份网表（${nand} 个与非门）。`,
    flowChipTitle: "想把它做成真的芯片？",
    flowChipNote: "把电路交给厂子，让它去烧。这一个文件里就带着网表和引脚数，那边不用手填；gatecraft 不碰钱包，也不发交易。",
    flowChipDownload: "下载导入文件",
    flowChipCopy: "或者直接复制",
    flowChipOpen: "打开 Firsto 的流片页 ↗",
    flowChipStep1: "下载这个文件（或者复制）。",
    flowChipStep2: "在那边导入，它会直接从文件里读出引脚数和门数。",
    flowChipStep3: "在那边连你自己的钱包，点流片。钱和交易都是你的，不经过我们。",
    flowChipOther: "换别的厂子，或者自己来",
    flowChipBlifNote: "BLIF 是通用格式：tapeout.net 的画布认它，Yosys、ABC、SIS 也认。但在那边会多花门：BLIF 读取器会把这颗电路里的反相器和输出缓冲重新算成独立的门（上面那个计数器从 35 变成 47），所以厂子如果接受上面的导入文件，就用那个。",
    flowChipCopyBlif: "复制 BLIF",
    flowChipManual: "或者自己生成未签名流片单（高级）",
    flowChipManualNote: "工作台会读你指定的链，写出交易让你自己核对签名，不连钱包。步骤更长，只有不走厂子自己的流程时才需要。",
    flowChipButton: "未签名流片单",
    file_circuit_blif: "给厂子的网表（BLIF）",
    file_app_html: "应用（单页）",
    file_circuit_firsto_json: "厂子的导入文件",
    sizeNand: (n) => `${n} 个与非门`,
    sizeWithLatch: (n, l) => `${n} 个与非门 · ${l} 个存储单元`,
    flowTick: "时钟走一拍",
    flowTryTitle: "拨一拨，看电路怎么回答",
    flowTrySub: "这里一个门一个门跑的，是真正会被做成芯片的那份电路，不是程序。",
    flowLiveTitle: "电路里正在发生什么",
    flowLiveCaption: "亮起来的线此刻是 1",
    flowLiveCaptionState: "亮起来的线此刻是 1；虚线把下一拍的状态送回存储单元",
    flowAgrees: "电路此刻的输出和程序一致。",
    flowYourSentence: "你说的那句话",
    flowHowToRead: "怎么看这张图",
    legendNand: "与非门（NAND）。整颗电路只用这一种门：两个输入都是 1 时输出 0，否则输出 1。",
    legendLatch: "存储单元（LATCH）。记住一位，时钟走一拍才更新。",
    legendWire: "亮起来的线此刻是 1，灰线是 0。",
    flowStartOver: "再说一句新的",
    modelAsks: "模型需要你说清楚一点，补进那句话里再问一次：",
    provider: "服务商",
    modelName: "模型",
    modelRequired: "必填",
    apiAddress: "API 地址",
    apiKey: "API key",
    apiKeyPlaceholder: "你自己的 key，费用记在你的账号上",
    rememberKey: "在这个浏览器里记住 key",
    byokNote: "那句话和 key 只从这个浏览器直接发给上面选的服务商；gatecraft 没有服务器，看不到它们。不勾选时，关掉页面 key 就忘了。OpenAI 兼容地址也可以是本机的模型服务（http://127.0.0.1:…）。模型写的程序不被接受时，会把错误给它看，再问一次。",
    askModel: "问模型",
    asking: "正在问…",
    askingAttempt: (n) => (n === 1 ? "等模型回复…" : `第一次的程序没通过检查，正在重问（第 ${n} 次）…`),
    gateChecking: "先看看这个能不能用一颗电路装下…",
    gateRestart: (n, k) => `换一张白纸重写（第 ${n} / ${k} 次）…`,
    gateNoTitle: "这个电路做不了",
    gateAskTitle: "还差一样东西",
    gateAnswer: "你的回答",
    gateSend: "就按这个，继续",
    gateSkip: "跳过检查，直接试",
    forkLooking: "先看有没有现成的形状能套…",
    forkPicked: (title) => `看着像「${title}」。读一遍，不是你要的就说一声。`,
    forkNotIt: "不是这个，从头写",
    playTitle: "按几下看看",
    playNever: "按这个键，它什么都不会变——多半是哪里理解错了",
    swapOffer: (rest) => (rest > 1 ? `拦路的有 ${rest} 处，其中这些可以换个做法——换完还得再看剩下的：` : "有个绕过去的办法："),
    askedOk: (n) => (n === 1 ? "模型写出了这段程序。编译前先读一遍。" : `模型第 ${n} 次写出了这段程序。编译前先读一遍。`),
    describeNote: "gatecraft 不替任何人付模型的钱：用你自己的模型，要么在下面填自己的 API key，要么复制提示词到你已经在用的助手里。",
    describePlaceholder: "例如：两个 6 位数，输出较大的那个，以及它们是否相等。",
    makePrompt: "生成提示词",
    copyPrompt: "复制提示词",
    describeEmpty: "先写一句话。",
    replyPlaceholder: "把模型的回复粘贴到这里",
    useReply: "使用这段程序",
    replyRejected: "这段回复用不了：",
    describeCheck: "下面的证明只保证电路和程序一致，不保证程序就是你那句话的意思。依赖它之前，先读一遍程序，再拨几个输入试试。",
    examplesTitle: "例子：给这些输入，应该得到这些输出",
    examplePlaceholder: "a=3 b=5 -> larger=5（有记忆时：press=1 count=9 -> then count=0）",
    addExample: "+ 例子",
    examplesHold: (n) => `${n} 个例子都对。`,
    examplesHoldProof: (n) => `${n} 个例子在程序上全部成立，电路又在每一行上和程序一致。`,
    readbackTitle: "这段程序用大白话说是",
    noExamplesYet: "还没有例子。加几个你知道答案的：编译前会逐个核对，有一个不对就不编译。",
    exprStates: "记忆（可选）：在时钟两拍之间保留的值，开机时是 0",
    nextIs: "位，下一拍 =",
    addState: "+ 记忆",
    exprOkState: (nIn, nState, rows, nOut) => `${nIn} 个输入位、${nState} 个记忆位，要复核 ${rows} 种组合，${nOut} 个输出位。`,
    tryNextState: "下一拍之后",
    readyMade: "现成的例子，不用 key：",
    noKeyTitle: "没有 key？复制提示词到任意聊天助手",
    needKey: "新的句子要用你自己的模型：在上面的模型设置里填 API key（或本机模型的地址），或者复制提示词到任意聊天助手。右边四句不用 key。",
    understandTitle: "它理解成了这样",
    thenWord: "之后记忆：",
    kind_expr: "表达式",
    hint_expr: "一句话下面的程序：输入的名字和位数、记忆、每个输出一个式子，例子在编译前逐个核对。",
    fn_expr: "表达式，例如 a > b ? a - b : b - a",
    exprInputs: "输入",
    exprLets: "共用定义（可选）",
    exprOutputs: "输出",
    exprName: "名字",
    exprWidth: "位",
    addInput: "+ 输入",
    addLet: "+ 定义",
    addOutput: "+ 输出",
    removeRow: "删除",
    exprOk: (nIn, rows, nOut) => `${nIn} 个输入位，要复核 ${rows} 行，${nOut} 个输出位。`,
    exprOkWide: (bits, max) => `输入加记忆 ${bits} 位，超过一次证明装得下的 ${max} 位；会拆成几块，各自证明。`,
    exprJson: "JSON 形式",
    exprJsonNote: "这段 JSON 就是完整的描述：命令行原样接受它，将来的自然语言前端也写这个格式。可以在这里修改或粘贴。",
    applyJson: "使用这段 JSON",
    exprSemantics: "值是精确整数，运算符和优先级照 JavaScript；每个输出对 2^位数 取模，负数像硬件一样回绕。位切片：a[3]、a[7:4]。",
    startsTitle: "起点电路，每个都在全表上核对过",
    frontEnd_bdd: "从真值表（BDD）合成",
    frontEnd_expression: "按表达式结构生成",
    startChosen: "被选中退火",
    startInexact: "有行不对，已丢弃",
    kind_grid: "决策图",
    kind_table: "真值表",
    kind_fsm: "状态机",
    hint_grid: "两个 4 位输入：X 选行，Y 选列。给 256 个组合逐格涂上电路应该做的选择。",
    hint_table: "最多 20 个输入位的任意函数。点击输出位修改，或者用关于 x 的表达式填满整张表。",
    hint_fsm: "对每个状态和每个输入，写出输出和下一个状态。电路上电时处于状态 0。",
    examples: "示例：",
    expression: "表达式",
    fill: "填入",
    fn_grid: "关于 x、y 的表达式，结果 0..3，例如 x > y ? 1 : 2",
    fn_table: "关于 x 的表达式，例如 (x & 1) ^ (x >> 1 & 1)",
    fn_fsm: "关于 x、s 的表达式，返回 [输出, 下一个状态]",
    fillAll: "用当前画笔涂满",
    choiceName: (k) => `选择 ${k} 的名字`,
    inputBits: "输入位数",
    outputBits: "输出位数",
    stateBits: "状态位数",
    previewRows: (shown, total) => `只显示前 ${shown} 行，共 ${total} 行。这么大的表请用表达式编辑。`,
    colInput: "输入 x",
    colState: "状态",
    colOutput: "输出",
    colNext: "下一个状态",
    graphTooBig: "状态图只在不超过 8 个状态、3 个输入位时绘制。",
    graphLegend: "箭头上的标注是「输入/输出」。粗圈是上电状态。",

    name: "名字",
    steps: "退火步数",
    seed: "种子",
    auto: "自动",
    fromTable: "取自表",
    objective: "优化目标",
    objective_gates: "NAND 最少",
    objective_cost: "PoD 成本最低",
    compile: "编译并证明",
    cancel: "取消",
    phase_synthesis: "从 BDD 合成 NAND 门…",
    phase_annealing: "缩小电路…",
    phase_verification: "逐行复核…",
    phase_block: "证明第几块",
    badName: "名字须是简短的小写短名，例如 my-circuit。",
    badSteps: "步数须是 1 到 1,000,000,000 的整数。",
    badSeed: "种子须是 0..4294967295 的整数，或 0x 开头的十六进制。",
    workerFailed: "编译线程没能启动。",
    labelEmpty: "每个选择都要有名字。",
    labelComma: "选择的名字里不能有逗号。",
    labelDuplicate: "选择的名字不能重复。",

    proofPlaceholder: "编译后这里显示证明：门数、深度，以及逐行复核的结果。",
    stale: "这次编译之后描述又改过了。重新编译才能证明新版本。",
    provenRows: "行已逐行复核，没有一行出错",
    provenFsm: "个（输入，状态）组合已复核，输出和下一个状态全部一致",
    methods: (m) => `复核方法：${m}。`,
    depth: "深度",
    podCost: "PoD 成本",
    bytes: "字节",
    shrink: (a, b) => `起点电路 ${a} 个 NAND，退火后缩到 ${b} 个。`,
    reachable: (a, b) => `从上电状态出发，${b} 个状态中能到达 ${a} 个。`,
    tableShape: (i, o) => `${i} 个输入位，${o} 个输出位。`,
    neverChosen: (list) => `永远不会选：${list}。`,
    everyChoiceUsed: "每个选择都至少出现一次。",
    reproduce: "复现",
    tableHash: "表的 SHA-256",
    netlistHash: "网表的 SHA-256",
    variableOrder: "BDD 变量顺序（从顶层起）",
    sifted: "经 sifting 重排",
    reproduceNote: "同一张表、同一个种子和步数，在任何机器上都得到相同的字节。下载规格文件后，用这条命令重建：",
    copy: "复制",
    copied: "已复制",
    downloadSpec: "命令行用的规格文件",

    tryInputs: "输入",
    tryState: "状态",
    tryOutputs: "输出",
    tick: "时钟走一拍",
    reset: "回到状态 0",
    agrees: "与表一致。",
    disagrees: "与表不一致。",
    traceTitle: "最近几拍",
    tooBigToDraw: (n) => `共 ${n} 个元件，画出来看不清。请下载网表查看。`,
    diagramAria: "电路图",
    diagramNote: "高亮的连线当前为 1。虚线连到 LATCH，决定下一拍的状态。",

    unsignedNotice: "gatecraft 只读取链上数据，生成未签名的流片单。它不会要求连接钱包或提供私钥，也不会发送任何交易。核对无误后，请按顺序用你自己的钱包签名发送。",
    rpc: "RPC 地址",
    rpcHint: "需要允许浏览器直接请求（CORS），否则请用命令行。",
    processor: "处理器合约地址",
    fromAddr: "你的钱包地址",
    fromHint: "只用来读取你持有的 NAND 和 LATCH 余额。",
    chainId: "链 ID",
    chainIdHint: "RPC 不在这条链上就拒绝。留空则不检查。",
    implementation: "预期实现合约地址",
    implementationHint: "处理器的 EIP-1967 实现地址不是它就拒绝。",
    optional: "可选",
    buildPlan: "读取链上数据并生成流片单",
    reading: "正在读取…",
    badRpc: "RPC 地址须以 http:// 或 https:// 开头。",
    badChainId: "链 ID 须是正整数。",
    rpcUnreachable: "浏览器连不上这个 RPC，可能是它不允许浏览器请求（CORS）。命令行没有这个限制：",
    block: "读取区块",
    expectedId: "预计电路编号",
    balances: "你的余额",
    fees: "费用",
    tapeoutFee: "流片",
    mintPrice: "单价",
    protocolFee: "协议费",
    total: "合计发送",
    guards: "已通过的检查",
    purpose: "用途",
    to: "发往",
    value: "金额",
    data: "调用数据",
    copyPlan: "复制流片单 JSON",
    downloadPlan: "下载流片单",
    idCaveat: "只有在你之前没有别人在这台处理器上流片，预计电路编号才成立。",
    nativeUnit: "原生代币",
    supplyLeft: "剩余可铸",
    simOk: (n, id, gas) => `已在读取的区块上模拟：${n} 笔交易按顺序全部成功，流片得到电路编号 ${id}，共 ${gas} gas。`,
    simToppedUp: "你的原生代币余额不够这些交易的总金额，模拟时临时补足了。签名前请先充值。",
    simFailed: "在读取的区块上模拟，这些交易会失败。不要签名。",
    simUnsupported: "这个 RPC 不支持 eth_simulateV1，交易单没有经过模拟。请仔细核对，或换一个支持模拟的 RPC。",
    wideTitle: (bits) => `输入加状态一共 ${bits} 位，一次证明装不下`,
    wideBody: "照样能做：每条规则各成一颗小电路，各自在自己的每一行上证明。怎么接起来由你定，因为它决定了上链的是什么。",
    wideLinked: "连成一颗（REF 引用）",
    wideLinkedHint: "一颗只有记忆和引用、自身没有逻辑的电路。先部署各块、填上编号，它就在链上当一颗跑。相同的块只部署一次。",
    wideReplay: "分开交付（按顺序重放）",
    wideReplayHint: "各块加一份运行顺序。状态由你的调用方自己保存，不用 REF。",
    composedBlocks: "块",
    bits: "位",
    composedEvery: "每一行",
    composedProven: (n) => `${n} 块，每块都在自己表的每一行上查过`,
    composedComputes: "算的是",
    composedReads: "位数 进 → 出",
    composedRows: "逐行正确",
    composedTop: (latch, refs) => `顶层电路是 ${latch} 个记忆加 ${refs} 个引用，自身没有一个与非门：接线里不可能藏着块里没有的错。`,
    composedEndToEnd: (rows, all) => `连成一颗、按序重放、程序本身三者在 ${rows} 行上一致${all ? "（全部行）" : "（例子加抽样；保证来自各块的逐行证明，这一步核对的是接线）"}。`,
    composedInlined: (names) => `这些名字可能为负，所以留在读它们的块里、不单独成块：${names}。`,
    composedNoSim: "逐步试跑和流片单只认一颗电路；分块的结果请下载下面的文件。连成一颗要先把各块部署好。",
    deliveryLinked: "按「连成一颗」交付：top.netlist.json 引用各块。",
    deliveryReplay: "按「分开交付」交付：replay.json 列出各块和顺序。",
  },
};
